// <copyright file="CreateAccountLiquidationBody.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;

namespace UpvestInvestmentApi.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for one-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<CreateAccountLiquidationBody>),
        new System.Type[] {
            typeof(AccountLiquidationRequestCase),
            typeof(AccountLiquidationRequest1Case)
        },
        true
    )]
    public abstract class CreateAccountLiquidationBody
    {
        /// <summary>
        /// This is Account liquidation - Request case.
        /// </summary>
        /// <returns>
        /// The CreateAccountLiquidationBody instance, wrapping the provided AccountLiquidationRequest value.
        /// </returns>
        public static CreateAccountLiquidationBody FromAccountLiquidationRequest(AccountLiquidationRequest accountLiquidationRequest)
        {
            return new AccountLiquidationRequestCase().Set(accountLiquidationRequest);
        }

        /// <summary>
        /// This is Account liquidation - Request1 case.
        /// </summary>
        /// <returns>
        /// The CreateAccountLiquidationBody instance, wrapping the provided AccountLiquidationRequest1 value.
        /// </returns>
        public static CreateAccountLiquidationBody FromAccountLiquidationRequest1(AccountLiquidationRequest1 accountLiquidationRequest1)
        {
            return new AccountLiquidationRequest1Case().Set(accountLiquidationRequest1);
        }

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(Func<AccountLiquidationRequest, T> accountLiquidationRequest, Func<AccountLiquidationRequest1, T> accountLiquidationRequest1);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(Func<AccountLiquidationRequest, T> accountLiquidationRequest = null, Func<AccountLiquidationRequest1, T> accountLiquidationRequest1 = null) =>
                Match(accountLiquidationRequest, accountLiquidationRequest1);

        [JsonConverter(typeof(UnionTypeCaseConverter<AccountLiquidationRequestCase, AccountLiquidationRequest>))]
        private sealed class AccountLiquidationRequestCase : CreateAccountLiquidationBody, ICaseValue<AccountLiquidationRequestCase, AccountLiquidationRequest>
        {
            public AccountLiquidationRequest Value;

            public override T Match<T>(Func<AccountLiquidationRequest, T> accountLiquidationRequest, Func<AccountLiquidationRequest1, T> accountLiquidationRequest1) =>
                   accountLiquidationRequest != null ? accountLiquidationRequest(Value) : default;

            public AccountLiquidationRequestCase Set(AccountLiquidationRequest value)
            {
                Value = value;
                return this;
            }

            public AccountLiquidationRequest Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<AccountLiquidationRequest1Case, AccountLiquidationRequest1>))]
        private sealed class AccountLiquidationRequest1Case : CreateAccountLiquidationBody, ICaseValue<AccountLiquidationRequest1Case, AccountLiquidationRequest1>
        {
            public AccountLiquidationRequest1 Value;

            public override T Match<T>(Func<AccountLiquidationRequest, T> accountLiquidationRequest, Func<AccountLiquidationRequest1, T> accountLiquidationRequest1) =>
                   accountLiquidationRequest1 != null ? accountLiquidationRequest1(Value) : default;

            public AccountLiquidationRequest1Case Set(AccountLiquidationRequest1 value)
            {
                Value = value;
                return this;
            }

            public AccountLiquidationRequest1 Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }
    }
}