// <copyright file="CreateReportResponse.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;

namespace UpvestInvestmentApi.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for one-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<CreateReportResponse>),
        new System.Type[] {
            typeof(UserReportOrderExAnteCostCase),
            typeof(BusinessReportOrderExAnteCostCase)
        },
        true
    )]
    public abstract class CreateReportResponse
    {
        /// <summary>
        /// This is User Report - Order ex-ante cost case.
        /// </summary>
        /// <returns>
        /// The CreateReportResponse instance, wrapping the provided UserReportOrderExAnteCost value.
        /// </returns>
        public static CreateReportResponse FromUserReportOrderExAnteCost(UserReportOrderExAnteCost userReportOrderExAnteCost)
        {
            return new UserReportOrderExAnteCostCase().Set(userReportOrderExAnteCost);
        }

        /// <summary>
        /// This is Business Report - Order ex-ante cost case.
        /// </summary>
        /// <returns>
        /// The CreateReportResponse instance, wrapping the provided BusinessReportOrderExAnteCost value.
        /// </returns>
        public static CreateReportResponse FromBusinessReportOrderExAnteCost(BusinessReportOrderExAnteCost businessReportOrderExAnteCost)
        {
            return new BusinessReportOrderExAnteCostCase().Set(businessReportOrderExAnteCost);
        }

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(Func<UserReportOrderExAnteCost, T> userReportOrderExAnteCost, Func<BusinessReportOrderExAnteCost, T> businessReportOrderExAnteCost);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(Func<UserReportOrderExAnteCost, T> userReportOrderExAnteCost = null, Func<BusinessReportOrderExAnteCost, T> businessReportOrderExAnteCost = null) =>
                Match(userReportOrderExAnteCost, businessReportOrderExAnteCost);

        [JsonConverter(typeof(UnionTypeCaseConverter<UserReportOrderExAnteCostCase, UserReportOrderExAnteCost>))]
        private sealed class UserReportOrderExAnteCostCase : CreateReportResponse, ICaseValue<UserReportOrderExAnteCostCase, UserReportOrderExAnteCost>
        {
            public UserReportOrderExAnteCost Value;

            public override T Match<T>(Func<UserReportOrderExAnteCost, T> userReportOrderExAnteCost, Func<BusinessReportOrderExAnteCost, T> businessReportOrderExAnteCost) =>
                   userReportOrderExAnteCost != null ? userReportOrderExAnteCost(Value) : default;

            public UserReportOrderExAnteCostCase Set(UserReportOrderExAnteCost value)
            {
                Value = value;
                return this;
            }

            public UserReportOrderExAnteCost Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<BusinessReportOrderExAnteCostCase, BusinessReportOrderExAnteCost>))]
        private sealed class BusinessReportOrderExAnteCostCase : CreateReportResponse, ICaseValue<BusinessReportOrderExAnteCostCase, BusinessReportOrderExAnteCost>
        {
            public BusinessReportOrderExAnteCost Value;

            public override T Match<T>(Func<UserReportOrderExAnteCost, T> userReportOrderExAnteCost, Func<BusinessReportOrderExAnteCost, T> businessReportOrderExAnteCost) =>
                   businessReportOrderExAnteCost != null ? businessReportOrderExAnteCost(Value) : default;

            public BusinessReportOrderExAnteCostCase Set(BusinessReportOrderExAnteCost value)
            {
                Value = value;
                return this;
            }

            public BusinessReportOrderExAnteCost Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }
    }
}