// <copyright file="ReportOrderExAnteCostCreateRequestRegularOrder.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;

namespace UpvestInvestmentApi.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for one-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<ReportOrderExAnteCostCreateRequestRegularOrder>),
        new System.Type[] {
            typeof(ExAnteCostUserOrderCase),
            typeof(ExAnteCostBusinessOrderCase)
        },
        true
    )]
    public abstract class ReportOrderExAnteCostCreateRequestRegularOrder
    {
        /// <summary>
        /// This is Ex-Ante cost user order case.
        /// </summary>
        /// <returns>
        /// The ReportOrderExAnteCostCreateRequestRegularOrder instance, wrapping the provided ExAnteCostUserOrder value.
        /// </returns>
        public static ReportOrderExAnteCostCreateRequestRegularOrder FromExAnteCostUserOrder(ExAnteCostUserOrder exAnteCostUserOrder)
        {
            return new ExAnteCostUserOrderCase().Set(exAnteCostUserOrder);
        }

        /// <summary>
        /// This is Ex-Ante Cost business order case.
        /// </summary>
        /// <returns>
        /// The ReportOrderExAnteCostCreateRequestRegularOrder instance, wrapping the provided ExAnteCostBusinessOrder value.
        /// </returns>
        public static ReportOrderExAnteCostCreateRequestRegularOrder FromExAnteCostBusinessOrder(ExAnteCostBusinessOrder exAnteCostBusinessOrder)
        {
            return new ExAnteCostBusinessOrderCase().Set(exAnteCostBusinessOrder);
        }

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(Func<ExAnteCostUserOrder, T> exAnteCostUserOrder, Func<ExAnteCostBusinessOrder, T> exAnteCostBusinessOrder);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(Func<ExAnteCostUserOrder, T> exAnteCostUserOrder = null, Func<ExAnteCostBusinessOrder, T> exAnteCostBusinessOrder = null) =>
                Match(exAnteCostUserOrder, exAnteCostBusinessOrder);

        [JsonConverter(typeof(UnionTypeCaseConverter<ExAnteCostUserOrderCase, ExAnteCostUserOrder>))]
        private sealed class ExAnteCostUserOrderCase : ReportOrderExAnteCostCreateRequestRegularOrder, ICaseValue<ExAnteCostUserOrderCase, ExAnteCostUserOrder>
        {
            public ExAnteCostUserOrder Value;

            public override T Match<T>(Func<ExAnteCostUserOrder, T> exAnteCostUserOrder, Func<ExAnteCostBusinessOrder, T> exAnteCostBusinessOrder) =>
                   exAnteCostUserOrder != null ? exAnteCostUserOrder(Value) : default;

            public ExAnteCostUserOrderCase Set(ExAnteCostUserOrder value)
            {
                Value = value;
                return this;
            }

            public ExAnteCostUserOrder Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<ExAnteCostBusinessOrderCase, ExAnteCostBusinessOrder>))]
        private sealed class ExAnteCostBusinessOrderCase : ReportOrderExAnteCostCreateRequestRegularOrder, ICaseValue<ExAnteCostBusinessOrderCase, ExAnteCostBusinessOrder>
        {
            public ExAnteCostBusinessOrder Value;

            public override T Match<T>(Func<ExAnteCostUserOrder, T> exAnteCostUserOrder, Func<ExAnteCostBusinessOrder, T> exAnteCostBusinessOrder) =>
                   exAnteCostBusinessOrder != null ? exAnteCostBusinessOrder(Value) : default;

            public ExAnteCostBusinessOrderCase Set(ExAnteCostBusinessOrder value)
            {
                Value = value;
                return this;
            }

            public ExAnteCostBusinessOrder Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }
    }
}