// <copyright file="RetrieveUserResponse.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;

namespace UpvestInvestmentApi.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for any-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<RetrieveUserResponse>),
        new System.Type[] {
            typeof(UserByolCase),
            typeof(UserTolCase)
        },
        false
    )]
    public abstract class RetrieveUserResponse
    {
        /// <summary>
        /// This is User (BYOL) case.
        /// </summary>
        /// <returns>
        /// The RetrieveUserResponse instance, wrapping the provided UserByol value.
        /// </returns>
        public static RetrieveUserResponse FromUserBYOL(UserByol userByol)
        {
            return new UserByolCase().Set(userByol);
        }

        /// <summary>
        /// This is User (TOL) case.
        /// </summary>
        /// <returns>
        /// The RetrieveUserResponse instance, wrapping the provided UserTol value.
        /// </returns>
        public static RetrieveUserResponse FromUserTOL(UserTol userTol)
        {
            return new UserTolCase().Set(userTol);
        }

        /// <summary>
        /// Method to match from the provided any-of cases. Here parameters
        /// represents the callback functions for any-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(Func<UserByol, T> userByol, Func<UserTol, T> userTol);

        /// <summary>
        /// Method to match from the provided any-of cases. The parameters represent
        /// optional callback functions for any-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(Func<UserByol, T> userByol = null, Func<UserTol, T> userTol = null) =>
                Match(userByol, userTol);

        [JsonConverter(typeof(UnionTypeCaseConverter<UserByolCase, UserByol>))]
        private sealed class UserByolCase : RetrieveUserResponse, ICaseValue<UserByolCase, UserByol>
        {
            public UserByol Value;

            public override T Match<T>(Func<UserByol, T> userByol, Func<UserTol, T> userTol) =>
                   userByol != null ? userByol(Value) : default;

            public UserByolCase Set(UserByol value)
            {
                Value = value;
                return this;
            }

            public UserByol Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<UserTolCase, UserTol>))]
        private sealed class UserTolCase : RetrieveUserResponse, ICaseValue<UserTolCase, UserTol>
        {
            public UserTol Value;

            public override T Match<T>(Func<UserByol, T> userByol, Func<UserTol, T> userTol) =>
                   userTol != null ? userTol(Value) : default;

            public UserTolCase Set(UserTol value)
            {
                Value = value;
                return this;
            }

            public UserTol Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }
    }
}