// <copyright file="RetrieveRoleResponse.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;

namespace UpvestInvestmentApi.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for one-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<RetrieveRoleResponse>),
        new System.Type[] {
            typeof(AccountGroupRoleCase),
            typeof(BusinessRoleCase)
        },
        true
    )]
    public abstract class RetrieveRoleResponse
    {
        /// <summary>
        /// This is Account Group Role case.
        /// </summary>
        /// <returns>
        /// The RetrieveRoleResponse instance, wrapping the provided AccountGroupRole value.
        /// </returns>
        public static RetrieveRoleResponse FromAccountGroupRole(AccountGroupRole accountGroupRole)
        {
            return new AccountGroupRoleCase().Set(accountGroupRole);
        }

        /// <summary>
        /// This is Business Role case.
        /// </summary>
        /// <returns>
        /// The RetrieveRoleResponse instance, wrapping the provided BusinessRole value.
        /// </returns>
        public static RetrieveRoleResponse FromBusinessRole(BusinessRole businessRole)
        {
            return new BusinessRoleCase().Set(businessRole);
        }

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(Func<AccountGroupRole, T> accountGroupRole, Func<BusinessRole, T> businessRole);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(Func<AccountGroupRole, T> accountGroupRole = null, Func<BusinessRole, T> businessRole = null) =>
                Match(accountGroupRole, businessRole);

        [JsonConverter(typeof(UnionTypeCaseConverter<AccountGroupRoleCase, AccountGroupRole>))]
        private sealed class AccountGroupRoleCase : RetrieveRoleResponse, ICaseValue<AccountGroupRoleCase, AccountGroupRole>
        {
            public AccountGroupRole Value;

            public override T Match<T>(Func<AccountGroupRole, T> accountGroupRole, Func<BusinessRole, T> businessRole) =>
                   accountGroupRole != null ? accountGroupRole(Value) : default;

            public AccountGroupRoleCase Set(AccountGroupRole value)
            {
                Value = value;
                return this;
            }

            public AccountGroupRole Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<BusinessRoleCase, BusinessRole>))]
        private sealed class BusinessRoleCase : RetrieveRoleResponse, ICaseValue<BusinessRoleCase, BusinessRole>
        {
            public BusinessRole Value;

            public override T Match<T>(Func<AccountGroupRole, T> accountGroupRole, Func<BusinessRole, T> businessRole) =>
                   businessRole != null ? businessRole(Value) : default;

            public BusinessRoleCase Set(BusinessRole value)
            {
                Value = value;
                return this;
            }

            public BusinessRole Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }
    }
}