// <copyright file="UsersListResponseDataCase0.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace UpvestInvestmentApi.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for any-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<UsersListResponseDataCase0>),
        new System.Type[] {
            typeof(ListOfUserByolCase),
            typeof(ListOfUserTolCase)
        },
        false
    )]
    public abstract class UsersListResponseDataCase0
    {
        /// <summary>
        /// This is List of User (BYOL) case.
        /// </summary>
        /// <returns>
        /// The UsersListResponseDataCase0 instance, wrapping the provided List&lt;UserByol&gt; value.
        /// </returns>
        public static UsersListResponseDataCase0 FromListOfUserBYOL(List<UserByol> listOfUserByol)
        {
            return new ListOfUserByolCase().Set(listOfUserByol);
        }

        /// <summary>
        /// This is List of User (TOL) case.
        /// </summary>
        /// <returns>
        /// The UsersListResponseDataCase0 instance, wrapping the provided List&lt;UserTol&gt; value.
        /// </returns>
        public static UsersListResponseDataCase0 FromListOfUserTOL(List<UserTol> listOfUserTol)
        {
            return new ListOfUserTolCase().Set(listOfUserTol);
        }

        /// <summary>
        /// Method to match from the provided any-of cases. Here parameters
        /// represents the callback functions for any-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(Func<List<UserByol>, T> listOfUserByol, Func<List<UserTol>, T> listOfUserTol);

        /// <summary>
        /// Method to match from the provided any-of cases. The parameters represent
        /// optional callback functions for any-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(Func<List<UserByol>, T> listOfUserByol = null, Func<List<UserTol>, T> listOfUserTol = null) =>
                Match(listOfUserByol, listOfUserTol);

        [JsonConverter(typeof(UnionTypeCaseConverter<ListOfUserByolCase, List<UserByol>>))]
        private sealed class ListOfUserByolCase : UsersListResponseDataCase0, ICaseValue<ListOfUserByolCase, List<UserByol>>
        {
            public List<UserByol> Value;

            public override T Match<T>(Func<List<UserByol>, T> listOfUserByol, Func<List<UserTol>, T> listOfUserTol) =>
                   listOfUserByol != null ? listOfUserByol(Value) : default;

            public ListOfUserByolCase Set(List<UserByol> value)
            {
                Value = value;
                return this;
            }

            public List<UserByol> Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<ListOfUserTolCase, List<UserTol>>))]
        private sealed class ListOfUserTolCase : UsersListResponseDataCase0, ICaseValue<ListOfUserTolCase, List<UserTol>>
        {
            public List<UserTol> Value;

            public override T Match<T>(Func<List<UserByol>, T> listOfUserByol, Func<List<UserTol>, T> listOfUserTol) =>
                   listOfUserTol != null ? listOfUserTol(Value) : default;

            public ListOfUserTolCase Set(List<UserTol> value)
            {
                Value = value;
                return this;
            }

            public List<UserTol> Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }
    }
}