// <copyright file="UsersListResponseData.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace UpvestInvestmentApi.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for one-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<UsersListResponseData>),
        new System.Type[] {
            typeof(Case0),
            typeof(ListOfObjectCase)
        },
        true
    )]
    public abstract class UsersListResponseData
    {
        /// <summary>
        /// This is UsersListResponseDataCase0 case.
        /// </summary>
        /// <returns>
        /// The UsersListResponseData instance, wrapping the provided UsersListResponseDataCase0 value.
        /// </returns>
        public static UsersListResponseData FromUsersListResponseDataCase0(UsersListResponseDataCase0 usersListResponseDataCase0)
        {
            return new Case0().Set(usersListResponseDataCase0);
        }

        /// <summary>
        /// This is List of Object case.
        /// </summary>
        /// <returns>
        /// The UsersListResponseData instance, wrapping the provided object value.
        /// </returns>
        public static UsersListResponseData FromListOfObject(object listOfObject)
        {
            return new ListOfObjectCase().Set(listOfObject);
        }

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(Func<UsersListResponseDataCase0, T> usersListResponseDataCase0, Func<object, T> listOfObject);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(Func<UsersListResponseDataCase0, T> usersListResponseDataCase0 = null, Func<object, T> listOfObject = null) =>
                Match(usersListResponseDataCase0, listOfObject);

        [JsonConverter(typeof(UnionTypeCaseConverter<Case0, UsersListResponseDataCase0>))]
        private sealed class Case0 : UsersListResponseData, ICaseValue<Case0, UsersListResponseDataCase0>
        {
            public UsersListResponseDataCase0 Value;

            public override T Match<T>(Func<UsersListResponseDataCase0, T> usersListResponseDataCase0, Func<object, T> listOfObject) =>
                   usersListResponseDataCase0 != null ? usersListResponseDataCase0(Value) : default;

            public Case0 Set(UsersListResponseDataCase0 value)
            {
                Value = value;
                return this;
            }

            public UsersListResponseDataCase0 Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<ListOfObjectCase, object>))]
        private sealed class ListOfObjectCase : UsersListResponseData, ICaseValue<ListOfObjectCase, object>
        {
            public object Value;

            public override T Match<T>(Func<UsersListResponseDataCase0, T> usersListResponseDataCase0, Func<object, T> listOfObject) =>
                   listOfObject != null ? listOfObject(Value) : default;

            public ListOfObjectCase Set(object value)
            {
                Value = value;
                return this;
            }

            public object Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }
    }
}