// <copyright file="CashBalanceTransfersApi.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Types;
using APIMatic.Core.Utilities;
using System;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using UpvestInvestmentApi.Standard.Exceptions;
using UpvestInvestmentApi.Standard.Http.Response;

namespace UpvestInvestmentApi.Standard.Apis
{
    /// <summary>
    /// CashBalanceTransfersApi.
    /// </summary>
    public class CashBalanceTransfersApi : BaseApi
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CashBalanceTransfersApi"/> class.
        /// </summary>
        internal CashBalanceTransfersApi(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Returns a paginated list of all cash balance transfers initiated by the client, across all account groups and users.
        /// </summary>
        /// <param name="upvestClientId">Required parameter: Your client ID, issued by Upvest. Identifies the client making the request. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestApiVersion">Optional parameter: Upvest API version (Note: Do not include quotation marks).</param>
        /// <param name="sort">Optional parameter: Field of resource to sort by.</param>
        /// <param name="order">Optional parameter: Sort order of the result list if the `sort` parameter is specified. Use `ASC` for ascending or `DESC` for descending sort order..</param>
        /// <param name="offset">Optional parameter: Use the `offset` argument to specify where in the list of results to start when returning items for a particular query..</param>
        /// <param name="limit">Optional parameter: Use the `limit` argument to specify the maximum number of items returned..</param>
        /// <returns>Returns the ApiResponse of Models.CashBalanceTransfersListResponse response from the API call.</returns>
        public ApiResponse<Models.CashBalanceTransfersListResponse> ListCashBalanceTransfers(
                Guid upvestClientId,
                Models.UpvestApiVersion? upvestApiVersion = Models.UpvestApiVersion.Enum1,
                Models.Sort4? sort = Models.Sort4.CreatedAt,
                Models.Order? order = Models.Order.Asc,
                int? offset = null,
                int? limit = 100)
            => CoreHelper.RunTask(ListCashBalanceTransfersAsync(upvestClientId, upvestApiVersion, sort, order, offset, limit));

        /// <summary>
        /// Returns a paginated list of all cash balance transfers initiated by the client, across all account groups and users.
        /// </summary>
        /// <param name="upvestClientId">Required parameter: Your client ID, issued by Upvest. Identifies the client making the request. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestApiVersion">Optional parameter: Upvest API version (Note: Do not include quotation marks).</param>
        /// <param name="sort">Optional parameter: Field of resource to sort by.</param>
        /// <param name="order">Optional parameter: Sort order of the result list if the `sort` parameter is specified. Use `ASC` for ascending or `DESC` for descending sort order..</param>
        /// <param name="offset">Optional parameter: Use the `offset` argument to specify where in the list of results to start when returning items for a particular query..</param>
        /// <param name="limit">Optional parameter: Use the `limit` argument to specify the maximum number of items returned..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.CashBalanceTransfersListResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.CashBalanceTransfersListResponse>> ListCashBalanceTransfersAsync(
                Guid upvestClientId,
                Models.UpvestApiVersion? upvestApiVersion = Models.UpvestApiVersion.Enum1,
                Models.Sort4? sort = Models.Sort4.CreatedAt,
                Models.Order? order = Models.Order.Asc,
                int? offset = null,
                int? limit = 100,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.CashBalanceTransfersListResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/payments/cash_balance_transfers")
                  .WithAuth("oauth-client-credentials")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("upvest-client-id", upvestClientId))
                      .Header(header => header.Setup("upvest-api-version", (upvestApiVersion.HasValue) ? CoreHelper.JsonSerialize(upvestApiVersion.Value).Trim('\"') : "1"))
                      .Query(query => query.Setup("sort", (sort.HasValue) ? CoreHelper.JsonSerialize(sort.Value).Trim('\"') : "created_at"))
                      .Query(query => query.Setup("order", (order.HasValue) ? CoreHelper.JsonSerialize(order.Value).Trim('\"') : "ASC"))
                      .Query(query => query.Setup("offset", offset))
                      .Query(query => query.Setup("limit", limit ?? 100))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Bad Request. The incoming request had a malformed parameter/object.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("401", CreateErrorCase("Unauthorized. The caller has not been authenticated.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("403", CreateErrorCase("Forbidden. The caller has been authenticated but is not allowed to take the requested action.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Not Found. The requested resource could not be found.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("406", CreateErrorCase("Not Acceptable. The resource does not have a current representation that would be acceptable to the user agent. \"Accept\" header defined unsupported value.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("429", CreateErrorCase("Too Many Requests. The caller has exceeded their quota for the time period and has been throttled.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("500", CreateErrorCase("Internal Server Error. The service encountered an unexpected error.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("503", CreateErrorCase("Service Unavailable. The service handling for this request cannot be reached at this time.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("504", CreateErrorCase("Gateway Timeout. The service gateway has reached its internal timeout.", (errorReason, context) => new ErrorException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Create an internal cash balance transfer between two account groups belonging to the same user and tenant. The cash leaves the source account group and arrives at the target account group as a single operation, with no external bank transfer. Only settled cash denominated in the same currency (EUR) can be transferred. Both account groups must be of the same type, and the type must be one of `PERSONAL`, `CHILD`, or `BUSINESS`.
        /// </summary>
        /// <param name="upvestClientId">Required parameter: Your client ID, issued by Upvest. Identifies the client making the request. Universally Unique Identifier (UUID)..</param>
        /// <param name="idempotencyKey">Required parameter: A UUID to be used as an idempotency key.  This prevents a duplicate request from being replayed. https://docs.upvest.co/documentation/concepts/api_concepts/idempotency.</param>
        /// <param name="upvestApiVersion">Optional parameter: Upvest API version (Note: Do not include quotation marks).</param>
        /// <param name="body">Optional parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.PaymentsCashBalanceTransfer response from the API call.</returns>
        public ApiResponse<Models.PaymentsCashBalanceTransfer> CreateCashBalanceTransfer(
                Guid upvestClientId,
                Guid idempotencyKey,
                Models.UpvestApiVersion? upvestApiVersion = Models.UpvestApiVersion.Enum1,
                Models.PaymentsCashBalanceTransferCreateRequest body = null)
            => CoreHelper.RunTask(CreateCashBalanceTransferAsync(upvestClientId, idempotencyKey, upvestApiVersion, body));

        /// <summary>
        /// Create an internal cash balance transfer between two account groups belonging to the same user and tenant. The cash leaves the source account group and arrives at the target account group as a single operation, with no external bank transfer. Only settled cash denominated in the same currency (EUR) can be transferred. Both account groups must be of the same type, and the type must be one of `PERSONAL`, `CHILD`, or `BUSINESS`.
        /// </summary>
        /// <param name="upvestClientId">Required parameter: Your client ID, issued by Upvest. Identifies the client making the request. Universally Unique Identifier (UUID)..</param>
        /// <param name="idempotencyKey">Required parameter: A UUID to be used as an idempotency key.  This prevents a duplicate request from being replayed. https://docs.upvest.co/documentation/concepts/api_concepts/idempotency.</param>
        /// <param name="upvestApiVersion">Optional parameter: Upvest API version (Note: Do not include quotation marks).</param>
        /// <param name="body">Optional parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.PaymentsCashBalanceTransfer response from the API call.</returns>
        public async Task<ApiResponse<Models.PaymentsCashBalanceTransfer>> CreateCashBalanceTransferAsync(
                Guid upvestClientId,
                Guid idempotencyKey,
                Models.UpvestApiVersion? upvestApiVersion = Models.UpvestApiVersion.Enum1,
                Models.PaymentsCashBalanceTransferCreateRequest body = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.PaymentsCashBalanceTransfer>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/payments/cash_balance_transfers")
                  .WithAuth("oauth-client-credentials")
                  .Parameters(parameters => parameters
                      .Body(b => b.Setup(body))
                      .Header(header => header.Setup("upvest-client-id", upvestClientId))
                      .Header(header => header.Setup("idempotency-key", idempotencyKey))
                      .Header(header => header.Setup("Content-Type", "application/json"))
                      .Header(header => header.Setup("upvest-api-version", (upvestApiVersion.HasValue) ? CoreHelper.JsonSerialize(upvestApiVersion.Value).Trim('\"') : "1"))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Bad Request. The incoming request had a malformed parameter/object.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("401", CreateErrorCase("Unauthorized. The caller has not been authenticated.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("403", CreateErrorCase("Forbidden. The caller has been authenticated but is not allowed to take the requested action.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Not Found. The requested resource could not be found.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("406", CreateErrorCase("Not Acceptable. The resource does not have a current representation that would be acceptable to the user agent. \"Accept\" header defined unsupported value.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("429", CreateErrorCase("Too Many Requests. The caller has exceeded their quota for the time period and has been throttled.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("500", CreateErrorCase("Internal Server Error. The service encountered an unexpected error.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("503", CreateErrorCase("Service Unavailable. The service handling for this request cannot be reached at this time.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("504", CreateErrorCase("Gateway Timeout. The service gateway has reached its internal timeout.", (errorReason, context) => new ErrorException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Retrieve a cash balance transfer by its ID.
        /// </summary>
        /// <param name="cashBalanceTransferId">Required parameter: The unique identifier of the cash balance transfer. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestClientId">Required parameter: Your client ID, issued by Upvest. Identifies the client making the request. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestApiVersion">Optional parameter: Upvest API version (Note: Do not include quotation marks).</param>
        /// <returns>Returns the ApiResponse of Models.PaymentsCashBalanceTransfer response from the API call.</returns>
        public ApiResponse<Models.PaymentsCashBalanceTransfer> RetrieveCashBalanceTransfer(
                Guid cashBalanceTransferId,
                Guid upvestClientId,
                Models.UpvestApiVersion? upvestApiVersion = Models.UpvestApiVersion.Enum1)
            => CoreHelper.RunTask(RetrieveCashBalanceTransferAsync(cashBalanceTransferId, upvestClientId, upvestApiVersion));

        /// <summary>
        /// Retrieve a cash balance transfer by its ID.
        /// </summary>
        /// <param name="cashBalanceTransferId">Required parameter: The unique identifier of the cash balance transfer. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestClientId">Required parameter: Your client ID, issued by Upvest. Identifies the client making the request. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestApiVersion">Optional parameter: Upvest API version (Note: Do not include quotation marks).</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.PaymentsCashBalanceTransfer response from the API call.</returns>
        public async Task<ApiResponse<Models.PaymentsCashBalanceTransfer>> RetrieveCashBalanceTransferAsync(
                Guid cashBalanceTransferId,
                Guid upvestClientId,
                Models.UpvestApiVersion? upvestApiVersion = Models.UpvestApiVersion.Enum1,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.PaymentsCashBalanceTransfer>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/payments/cash_balance_transfers/{cash_balance_transfer_id}")
                  .WithAuth("oauth-client-credentials")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("cash_balance_transfer_id", cashBalanceTransferId))
                      .Header(header => header.Setup("upvest-client-id", upvestClientId))
                      .Header(header => header.Setup("upvest-api-version", (upvestApiVersion.HasValue) ? CoreHelper.JsonSerialize(upvestApiVersion.Value).Trim('\"') : "1"))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("401", CreateErrorCase("Unauthorized. The caller has not been authenticated.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("403", CreateErrorCase("Forbidden. The caller has been authenticated but is not allowed to take the requested action.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Not Found. The requested resource could not be found.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("406", CreateErrorCase("Not Acceptable. The resource does not have a current representation that would be acceptable to the user agent. \"Accept\" header defined unsupported value.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("429", CreateErrorCase("Too Many Requests. The caller has exceeded their quota for the time period and has been throttled.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("500", CreateErrorCase("Internal Server Error. The service encountered an unexpected error.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("503", CreateErrorCase("Service Unavailable. The service handling for this request cannot be reached at this time.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("504", CreateErrorCase("Gateway Timeout. The service gateway has reached its internal timeout.", (errorReason, context) => new ErrorException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Cancels a cash balance transfer specified by its ID. It is only possible to cancel a transfer while it has the status `ISSUED`.
        /// </summary>
        /// <param name="cashBalanceTransferId">Required parameter: The unique identifier of the cash balance transfer. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestClientId">Required parameter: Your client ID, issued by Upvest. Identifies the client making the request. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestApiVersion">Optional parameter: Upvest API version (Note: Do not include quotation marks).</param>
        public void CancelCashBalanceTransfer(
                Guid cashBalanceTransferId,
                Guid upvestClientId,
                Models.UpvestApiVersion? upvestApiVersion = Models.UpvestApiVersion.Enum1)
            => CoreHelper.RunVoidTask(CancelCashBalanceTransferAsync(cashBalanceTransferId, upvestClientId, upvestApiVersion));

        /// <summary>
        /// Cancels a cash balance transfer specified by its ID. It is only possible to cancel a transfer while it has the status `ISSUED`.
        /// </summary>
        /// <param name="cashBalanceTransferId">Required parameter: The unique identifier of the cash balance transfer. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestClientId">Required parameter: Your client ID, issued by Upvest. Identifies the client making the request. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestApiVersion">Optional parameter: Upvest API version (Note: Do not include quotation marks).</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the void response from the API call.</returns>
        public async Task CancelCashBalanceTransferAsync(
                Guid cashBalanceTransferId,
                Guid upvestClientId,
                Models.UpvestApiVersion? upvestApiVersion = Models.UpvestApiVersion.Enum1,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<VoidType>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Delete, "/payments/cash_balance_transfers/{cash_balance_transfer_id}")
                  .WithAuth("oauth-client-credentials")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("cash_balance_transfer_id", cashBalanceTransferId))
                      .Header(header => header.Setup("upvest-client-id", upvestClientId))
                      .Header(header => header.Setup("upvest-api-version", (upvestApiVersion.HasValue) ? CoreHelper.JsonSerialize(upvestApiVersion.Value).Trim('\"') : "1"))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("401", CreateErrorCase("Unauthorized. The caller has not been authenticated.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("403", CreateErrorCase("Forbidden. The caller has been authenticated but is not allowed to take the requested action.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Not Found. The requested resource could not be found.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("422", CreateErrorCase("Unprocessable Entity. The syntax of request is correct but server can't process it due a semantic error.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("429", CreateErrorCase("Too Many Requests. The caller has exceeded their quota for the time period and has been throttled.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("500", CreateErrorCase("Internal Server Error. The service encountered an unexpected error.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("503", CreateErrorCase("Service Unavailable. The service handling for this request cannot be reached at this time.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("504", CreateErrorCase("Gateway Timeout. The service gateway has reached its internal timeout.", (errorReason, context) => new ErrorException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Returns the list of cash balance transfers of a user specified by ID.
        /// </summary>
        /// <param name="userId">Required parameter: The unique identifier of the user. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestClientId">Required parameter: Your client ID, issued by Upvest. Identifies the client making the request. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestApiVersion">Optional parameter: Upvest API version (Note: Do not include quotation marks).</param>
        /// <param name="sort">Optional parameter: Field of resource to sort by.</param>
        /// <param name="order">Optional parameter: Sort order of the result list if the `sort` parameter is specified. Use `ASC` for ascending or `DESC` for descending sort order..</param>
        /// <param name="offset">Optional parameter: Use the `offset` argument to specify where in the list of results to start when returning items for a particular query..</param>
        /// <param name="limit">Optional parameter: Use the `limit` argument to specify the maximum number of items returned..</param>
        /// <returns>Returns the ApiResponse of Models.UserCashBalanceTransfersListResponse response from the API call.</returns>
        public ApiResponse<Models.UserCashBalanceTransfersListResponse> ListUserCashBalanceTransfers(
                Guid userId,
                Guid upvestClientId,
                Models.UpvestApiVersion? upvestApiVersion = Models.UpvestApiVersion.Enum1,
                Models.Sort4? sort = Models.Sort4.CreatedAt,
                Models.Order? order = Models.Order.Asc,
                int? offset = null,
                int? limit = 100)
            => CoreHelper.RunTask(ListUserCashBalanceTransfersAsync(userId, upvestClientId, upvestApiVersion, sort, order, offset, limit));

        /// <summary>
        /// Returns the list of cash balance transfers of a user specified by ID.
        /// </summary>
        /// <param name="userId">Required parameter: The unique identifier of the user. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestClientId">Required parameter: Your client ID, issued by Upvest. Identifies the client making the request. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestApiVersion">Optional parameter: Upvest API version (Note: Do not include quotation marks).</param>
        /// <param name="sort">Optional parameter: Field of resource to sort by.</param>
        /// <param name="order">Optional parameter: Sort order of the result list if the `sort` parameter is specified. Use `ASC` for ascending or `DESC` for descending sort order..</param>
        /// <param name="offset">Optional parameter: Use the `offset` argument to specify where in the list of results to start when returning items for a particular query..</param>
        /// <param name="limit">Optional parameter: Use the `limit` argument to specify the maximum number of items returned..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.UserCashBalanceTransfersListResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.UserCashBalanceTransfersListResponse>> ListUserCashBalanceTransfersAsync(
                Guid userId,
                Guid upvestClientId,
                Models.UpvestApiVersion? upvestApiVersion = Models.UpvestApiVersion.Enum1,
                Models.Sort4? sort = Models.Sort4.CreatedAt,
                Models.Order? order = Models.Order.Asc,
                int? offset = null,
                int? limit = 100,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.UserCashBalanceTransfersListResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/users/{user_id}/payments/cash_balance_transfers")
                  .WithAuth("oauth-client-credentials")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("user_id", userId))
                      .Header(header => header.Setup("upvest-client-id", upvestClientId))
                      .Header(header => header.Setup("upvest-api-version", (upvestApiVersion.HasValue) ? CoreHelper.JsonSerialize(upvestApiVersion.Value).Trim('\"') : "1"))
                      .Query(query => query.Setup("sort", (sort.HasValue) ? CoreHelper.JsonSerialize(sort.Value).Trim('\"') : "created_at"))
                      .Query(query => query.Setup("order", (order.HasValue) ? CoreHelper.JsonSerialize(order.Value).Trim('\"') : "ASC"))
                      .Query(query => query.Setup("offset", offset))
                      .Query(query => query.Setup("limit", limit ?? 100))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Bad Request. The incoming request had a malformed parameter/object.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("401", CreateErrorCase("Unauthorized. The caller has not been authenticated.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("403", CreateErrorCase("Forbidden. The caller has been authenticated but is not allowed to take the requested action.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Not Found. The requested resource could not be found.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("406", CreateErrorCase("Not Acceptable. The resource does not have a current representation that would be acceptable to the user agent. \"Accept\" header defined unsupported value.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("429", CreateErrorCase("Too Many Requests. The caller has exceeded their quota for the time period and has been throttled.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("500", CreateErrorCase("Internal Server Error. The service encountered an unexpected error.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("503", CreateErrorCase("Service Unavailable. The service handling for this request cannot be reached at this time.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("504", CreateErrorCase("Gateway Timeout. The service gateway has reached its internal timeout.", (errorReason, context) => new ErrorException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Returns the list of cash balance transfers of a business specified by ID.
        /// </summary>
        /// <param name="businessId">Required parameter: The unique identifier of the business. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestClientId">Required parameter: Your client ID, issued by Upvest. Identifies the client making the request. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestApiVersion">Optional parameter: Upvest API version (Note: Do not include quotation marks).</param>
        /// <param name="sort">Optional parameter: Field of resource to sort by.</param>
        /// <param name="order">Optional parameter: Sort order of the result list if the `sort` parameter is specified. Use `ASC` for ascending or `DESC` for descending sort order..</param>
        /// <param name="offset">Optional parameter: Use the `offset` argument to specify where in the list of results to start when returning items for a particular query..</param>
        /// <param name="limit">Optional parameter: Use the `limit` argument to specify the maximum number of items returned..</param>
        /// <returns>Returns the ApiResponse of Models.BusinessCashBalanceTransfersListResponse response from the API call.</returns>
        public ApiResponse<Models.BusinessCashBalanceTransfersListResponse> ListBusinessCashBalanceTransfers(
                Guid businessId,
                Guid upvestClientId,
                Models.UpvestApiVersion? upvestApiVersion = Models.UpvestApiVersion.Enum1,
                Models.Sort4? sort = Models.Sort4.CreatedAt,
                Models.Order? order = Models.Order.Asc,
                int? offset = null,
                int? limit = 100)
            => CoreHelper.RunTask(ListBusinessCashBalanceTransfersAsync(businessId, upvestClientId, upvestApiVersion, sort, order, offset, limit));

        /// <summary>
        /// Returns the list of cash balance transfers of a business specified by ID.
        /// </summary>
        /// <param name="businessId">Required parameter: The unique identifier of the business. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestClientId">Required parameter: Your client ID, issued by Upvest. Identifies the client making the request. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestApiVersion">Optional parameter: Upvest API version (Note: Do not include quotation marks).</param>
        /// <param name="sort">Optional parameter: Field of resource to sort by.</param>
        /// <param name="order">Optional parameter: Sort order of the result list if the `sort` parameter is specified. Use `ASC` for ascending or `DESC` for descending sort order..</param>
        /// <param name="offset">Optional parameter: Use the `offset` argument to specify where in the list of results to start when returning items for a particular query..</param>
        /// <param name="limit">Optional parameter: Use the `limit` argument to specify the maximum number of items returned..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.BusinessCashBalanceTransfersListResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.BusinessCashBalanceTransfersListResponse>> ListBusinessCashBalanceTransfersAsync(
                Guid businessId,
                Guid upvestClientId,
                Models.UpvestApiVersion? upvestApiVersion = Models.UpvestApiVersion.Enum1,
                Models.Sort4? sort = Models.Sort4.CreatedAt,
                Models.Order? order = Models.Order.Asc,
                int? offset = null,
                int? limit = 100,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.BusinessCashBalanceTransfersListResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/businesses/{business_id}/payments/cash_balance_transfers")
                  .WithAuth("oauth-client-credentials")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("business_id", businessId))
                      .Header(header => header.Setup("upvest-client-id", upvestClientId))
                      .Header(header => header.Setup("upvest-api-version", (upvestApiVersion.HasValue) ? CoreHelper.JsonSerialize(upvestApiVersion.Value).Trim('\"') : "1"))
                      .Query(query => query.Setup("sort", (sort.HasValue) ? CoreHelper.JsonSerialize(sort.Value).Trim('\"') : "created_at"))
                      .Query(query => query.Setup("order", (order.HasValue) ? CoreHelper.JsonSerialize(order.Value).Trim('\"') : "ASC"))
                      .Query(query => query.Setup("offset", offset))
                      .Query(query => query.Setup("limit", limit ?? 100))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Bad Request. The incoming request had a malformed parameter/object.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("401", CreateErrorCase("Unauthorized. The caller has not been authenticated.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("403", CreateErrorCase("Forbidden. The caller has been authenticated but is not allowed to take the requested action.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Not Found. The requested resource could not be found.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("406", CreateErrorCase("Not Acceptable. The resource does not have a current representation that would be acceptable to the user agent. \"Accept\" header defined unsupported value.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("429", CreateErrorCase("Too Many Requests. The caller has exceeded their quota for the time period and has been throttled.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("500", CreateErrorCase("Internal Server Error. The service encountered an unexpected error.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("503", CreateErrorCase("Service Unavailable. The service handling for this request cannot be reached at this time.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("504", CreateErrorCase("Gateway Timeout. The service gateway has reached its internal timeout.", (errorReason, context) => new ErrorException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}