// <copyright file="SecuritiesTransfersApi.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using System;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using UpvestInvestmentApi.Standard.Exceptions;
using UpvestInvestmentApi.Standard.Http.Response;

namespace UpvestInvestmentApi.Standard.Apis
{
    /// <summary>
    /// SecuritiesTransfersApi.
    /// </summary>
    public class SecuritiesTransfersApi : BaseApi
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SecuritiesTransfersApi"/> class.
        /// </summary>
        internal SecuritiesTransfersApi(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Returns the list of securities transfers.
        /// Restrict the list to one direction with the `direction` query parameter, and page through results with the `offset` and `limit` query parameters; `meta.total_count` gives the total number of matching transfers.
        /// See the securities transfers guide ([TOL](https://docs.upvest.co/products/tol/guides/transfers/securities_transfers_overview) / [BYOL](https://docs.upvest.co/products/byol/guides/transfers/securities_transfers_overview) / [Omnibus](https://docs.upvest.co/products/omnibus/guides/transfers/securities_transfers_overview)) for the transfer stages and settlement details.
        /// </summary>
        /// <param name="upvestClientId">Required parameter: Your client ID, issued by Upvest. Identifies the client making the request. Universally Unique Identifier (UUID)..</param>
        /// <param name="direction">Required parameter: Filter the list by transfer direction..</param>
        /// <param name="upvestApiVersion">Optional parameter: Upvest API version (Note: Do not include quotation marks).</param>
        /// <param name="sort">Optional parameter: Sort the result by `created_at`, `updated_at`..</param>
        /// <param name="order">Optional parameter: Sort order of the result list if the `sort` parameter is specified. Use `ASC` for ascending or `DESC` for descending sort order..</param>
        /// <param name="offset">Optional parameter: Use the `offset` argument to specify where in the list of results to start when returning items for a particular query..</param>
        /// <param name="limit">Optional parameter: Use the `limit` argument to specify the maximum number of items returned..</param>
        /// <param name="userId">Optional parameter: Filters results by user ID. Universally Unique Identifier (UUID)..</param>
        /// <param name="accountId">Optional parameter: Filters results by account ID. Universally Unique Identifier (UUID)..</param>
        /// <param name="accountGroupId">Optional parameter: Filters results by account group ID. Universally Unique Identifier (UUID)..</param>
        /// <param name="status">Optional parameter: Status of the securities transfer  * NEW - Securities transfer is created but not started processing.  * PROCESSING - Securities transfer is in processing.  * SETTLED - Securities transfer was successfully settled.  * CANCELLED - Securities transfer was cancelled..</param>
        /// <returns>Returns the ApiResponse of Models.SecurityTransfersListResponse response from the API call.</returns>
        public ApiResponse<Models.SecurityTransfersListResponse> ListSecuritiesTransfers(
                Guid upvestClientId,
                string authorization,
                string signature,
                string signatureInput,
                Models.Direction direction,
                Models.UpvestApiVersion? upvestApiVersion = Models.UpvestApiVersion.Enum1,
                Models.Sort1? sort = Models.Sort1.CreatedAt,
                Models.Order? order = Models.Order.Asc,
                int? offset = null,
                int? limit = 100,
                Guid? userId = null,
                Guid? accountId = null,
                Guid? accountGroupId = null,
                Models.Status78? status = null)
            => CoreHelper.RunTask(ListSecuritiesTransfersAsync(upvestClientId, authorization, signature, signatureInput, direction, upvestApiVersion, sort, order, offset, limit, userId, accountId, accountGroupId, status));

        /// <summary>
        /// Returns the list of securities transfers.
        /// Restrict the list to one direction with the `direction` query parameter, and page through results with the `offset` and `limit` query parameters; `meta.total_count` gives the total number of matching transfers.
        /// See the securities transfers guide ([TOL](https://docs.upvest.co/products/tol/guides/transfers/securities_transfers_overview) / [BYOL](https://docs.upvest.co/products/byol/guides/transfers/securities_transfers_overview) / [Omnibus](https://docs.upvest.co/products/omnibus/guides/transfers/securities_transfers_overview)) for the transfer stages and settlement details.
        /// </summary>
        /// <param name="upvestClientId">Required parameter: Your client ID, issued by Upvest. Identifies the client making the request. Universally Unique Identifier (UUID)..</param>
        /// <param name="direction">Required parameter: Filter the list by transfer direction..</param>
        /// <param name="upvestApiVersion">Optional parameter: Upvest API version (Note: Do not include quotation marks).</param>
        /// <param name="sort">Optional parameter: Sort the result by `created_at`, `updated_at`..</param>
        /// <param name="order">Optional parameter: Sort order of the result list if the `sort` parameter is specified. Use `ASC` for ascending or `DESC` for descending sort order..</param>
        /// <param name="offset">Optional parameter: Use the `offset` argument to specify where in the list of results to start when returning items for a particular query..</param>
        /// <param name="limit">Optional parameter: Use the `limit` argument to specify the maximum number of items returned..</param>
        /// <param name="userId">Optional parameter: Filters results by user ID. Universally Unique Identifier (UUID)..</param>
        /// <param name="accountId">Optional parameter: Filters results by account ID. Universally Unique Identifier (UUID)..</param>
        /// <param name="accountGroupId">Optional parameter: Filters results by account group ID. Universally Unique Identifier (UUID)..</param>
        /// <param name="status">Optional parameter: Status of the securities transfer  * NEW - Securities transfer is created but not started processing.  * PROCESSING - Securities transfer is in processing.  * SETTLED - Securities transfer was successfully settled.  * CANCELLED - Securities transfer was cancelled..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.SecurityTransfersListResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.SecurityTransfersListResponse>> ListSecuritiesTransfersAsync(
                Guid upvestClientId,
                string authorization,
                string signature,
                string signatureInput,
                Models.Direction direction,
                Models.UpvestApiVersion? upvestApiVersion = Models.UpvestApiVersion.Enum1,
                Models.Sort1? sort = Models.Sort1.CreatedAt,
                Models.Order? order = Models.Order.Asc,
                int? offset = null,
                int? limit = 100,
                Guid? userId = null,
                Guid? accountId = null,
                Guid? accountGroupId = null,
                Models.Status78? status = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.SecurityTransfersListResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/securities_transfers")
                  .WithAuth("oauth-client-credentials")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("upvest-client-id", upvestClientId))
                      .Query(query => query.Setup("direction", CoreHelper.JsonSerialize(direction).Trim('\"')))
                      .Header(header => header.Setup("upvest-api-version", (upvestApiVersion.HasValue) ? CoreHelper.JsonSerialize(upvestApiVersion.Value).Trim('\"') : "1"))
                      .Query(query => query.Setup("sort", (sort.HasValue) ? CoreHelper.JsonSerialize(sort.Value).Trim('\"') : "created_at"))
                      .Query(query => query.Setup("order", (order.HasValue) ? CoreHelper.JsonSerialize(order.Value).Trim('\"') : "ASC"))
                      .Query(query => query.Setup("offset", offset))
                      .Query(query => query.Setup("limit", limit ?? 100))
                      .Query(query => query.Setup("user_id", userId))
                      .Query(query => query.Setup("account_id", accountId))
                      .Query(query => query.Setup("account_group_id", accountGroupId))
                      .Query(query => query.Setup("status", (status.HasValue) ? CoreHelper.JsonSerialize(status.Value).Trim('\"') : null))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Bad Request. The incoming request had a malformed parameter/object.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("401", CreateErrorCase("Unauthorized. The caller has not been authenticated.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("403", CreateErrorCase("Forbidden. The caller has been authenticated but is not allowed to take the requested action.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("406", CreateErrorCase("Not Acceptable. The resource does not have a current representation that would be acceptable to the user agent. \"Accept\" header defined unsupported value.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("429", CreateErrorCase("Too Many Requests. The caller has exceeded their quota for the time period and has been throttled.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("500", CreateErrorCase("Internal Server Error. The service encountered an unexpected error.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("503", CreateErrorCase("Service Unavailable. The service handling for this request cannot be reached at this time.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("504", CreateErrorCase("Gateway Timeout. The service gateway has reached its internal timeout.", (errorReason, context) => new ErrorException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Creates a securities transfer, moving a position in a single instrument between an Upvest account and an external custodian.
        /// Set `direction` to `INCOMING` to move securities into an Upvest account, or `OUTGOING` to move them out to an external custodian. Only full units can be transferred — fractional quantities are not supported by the SWIFT messaging used for settlement. Unfulfilled incoming transfer requests are cancelled automatically after 30 days.
        /// See the securities transfers guide ([TOL](https://docs.upvest.co/products/tol/guides/transfers/securities_transfers_overview) / [BYOL](https://docs.upvest.co/products/byol/guides/transfers/securities_transfers_overview) / [Omnibus](https://docs.upvest.co/products/omnibus/guides/transfers/securities_transfers_overview)) for the transfer stages and settlement details.
        /// </summary>
        /// <param name="upvestClientId">Required parameter: Your client ID, issued by Upvest. Identifies the client making the request. Universally Unique Identifier (UUID)..</param>
        /// <param name="idempotencyKey">Required parameter: A UUID to be used as an idempotency key.  This prevents a duplicate request from being replayed. https://docs.upvest.co/documentation/concepts/api_concepts/idempotency.</param>
        /// <param name="upvestApiVersion">Optional parameter: Upvest API version (Note: Do not include quotation marks).</param>
        /// <param name="body">Optional parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.SecuritiesTransfersResponse response from the API call.</returns>
        public ApiResponse<Models.SecuritiesTransfersResponse> CreateSecuritiesTransfer(
                Guid upvestClientId,
                Guid idempotencyKey,
                Models.UpvestApiVersion? upvestApiVersion = Models.UpvestApiVersion.Enum1,
                Models.TransfersSecuritiesTransferCreateRequest body = null)
            => CoreHelper.RunTask(CreateSecuritiesTransferAsync(upvestClientId, idempotencyKey, upvestApiVersion, body));

        /// <summary>
        /// Creates a securities transfer, moving a position in a single instrument between an Upvest account and an external custodian.
        /// Set `direction` to `INCOMING` to move securities into an Upvest account, or `OUTGOING` to move them out to an external custodian. Only full units can be transferred — fractional quantities are not supported by the SWIFT messaging used for settlement. Unfulfilled incoming transfer requests are cancelled automatically after 30 days.
        /// See the securities transfers guide ([TOL](https://docs.upvest.co/products/tol/guides/transfers/securities_transfers_overview) / [BYOL](https://docs.upvest.co/products/byol/guides/transfers/securities_transfers_overview) / [Omnibus](https://docs.upvest.co/products/omnibus/guides/transfers/securities_transfers_overview)) for the transfer stages and settlement details.
        /// </summary>
        /// <param name="upvestClientId">Required parameter: Your client ID, issued by Upvest. Identifies the client making the request. Universally Unique Identifier (UUID)..</param>
        /// <param name="idempotencyKey">Required parameter: A UUID to be used as an idempotency key.  This prevents a duplicate request from being replayed. https://docs.upvest.co/documentation/concepts/api_concepts/idempotency.</param>
        /// <param name="upvestApiVersion">Optional parameter: Upvest API version (Note: Do not include quotation marks).</param>
        /// <param name="body">Optional parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.SecuritiesTransfersResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.SecuritiesTransfersResponse>> CreateSecuritiesTransferAsync(
                Guid upvestClientId,
                Guid idempotencyKey,
                Models.UpvestApiVersion? upvestApiVersion = Models.UpvestApiVersion.Enum1,
                Models.TransfersSecuritiesTransferCreateRequest body = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.SecuritiesTransfersResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/securities_transfers")
                  .WithAuth("oauth-client-credentials")
                  .Parameters(parameters => parameters
                      .Body(b => b.Setup(body))
                      .Header(header => header.Setup("upvest-client-id", upvestClientId))
                      .Header(header => header.Setup("idempotency-key", idempotencyKey))
                      .Header(header => header.Setup("Content-Type", "application/json"))
                      .Header(header => header.Setup("upvest-api-version", (upvestApiVersion.HasValue) ? CoreHelper.JsonSerialize(upvestApiVersion.Value).Trim('\"') : "1"))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Bad Request. The incoming request had a malformed parameter/object.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("401", CreateErrorCase("Unauthorized. The caller has not been authenticated.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("403", CreateErrorCase("Forbidden. The caller has been authenticated but is not allowed to take the requested action.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Not Found. The requested resource could not be found.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("406", CreateErrorCase("Not Acceptable. The resource does not have a current representation that would be acceptable to the user agent. \"Accept\" header defined unsupported value.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("429", CreateErrorCase("Too Many Requests. The caller has exceeded their quota for the time period and has been throttled.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("500", CreateErrorCase("Internal Server Error. The service encountered an unexpected error.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("503", CreateErrorCase("Service Unavailable. The service handling for this request cannot be reached at this time.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("504", CreateErrorCase("Gateway Timeout. The service gateway has reached its internal timeout.", (errorReason, context) => new ErrorException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}