// <copyright file="TaxExemptionsApi.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Types;
using APIMatic.Core.Utilities;
using System;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using UpvestInvestmentApi.Standard.Exceptions;
using UpvestInvestmentApi.Standard.Http.Response;

namespace UpvestInvestmentApi.Standard.Apis
{
    /// <summary>
    /// TaxExemptionsApi.
    /// </summary>
    public class TaxExemptionsApi : BaseApi
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TaxExemptionsApi"/> class.
        /// </summary>
        internal TaxExemptionsApi(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Creates a tax exemption.
        /// </summary>
        /// <param name="upvestClientId">Required parameter: Your client ID, issued by Upvest. Identifies the client making the request. Universally Unique Identifier (UUID)..</param>
        /// <param name="idempotencyKey">Required parameter: A UUID to be used as an idempotency key.  This prevents a duplicate request from being replayed. https://docs.upvest.co/documentation/concepts/api_concepts/idempotency.</param>
        /// <param name="upvestApiVersion">Optional parameter: Upvest API version (Note: Do not include quotation marks).</param>
        /// <param name="body">Optional parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.TaxExemptionsCreateResponse response from the API call.</returns>
        public ApiResponse<Models.TaxExemptionsCreateResponse> CreateTaxExemption(
                Guid upvestClientId,
                Guid idempotencyKey,
                Models.UpvestApiVersion? upvestApiVersion = Models.UpvestApiVersion.Enum1,
                Models.TaxesTaxExemptionsCreateRequest body = null)
            => CoreHelper.RunTask(CreateTaxExemptionAsync(upvestClientId, idempotencyKey, upvestApiVersion, body));

        /// <summary>
        /// Creates a tax exemption.
        /// </summary>
        /// <param name="upvestClientId">Required parameter: Your client ID, issued by Upvest. Identifies the client making the request. Universally Unique Identifier (UUID)..</param>
        /// <param name="idempotencyKey">Required parameter: A UUID to be used as an idempotency key.  This prevents a duplicate request from being replayed. https://docs.upvest.co/documentation/concepts/api_concepts/idempotency.</param>
        /// <param name="upvestApiVersion">Optional parameter: Upvest API version (Note: Do not include quotation marks).</param>
        /// <param name="body">Optional parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.TaxExemptionsCreateResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.TaxExemptionsCreateResponse>> CreateTaxExemptionAsync(
                Guid upvestClientId,
                Guid idempotencyKey,
                Models.UpvestApiVersion? upvestApiVersion = Models.UpvestApiVersion.Enum1,
                Models.TaxesTaxExemptionsCreateRequest body = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.TaxExemptionsCreateResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/tax_exemptions")
                  .WithAuth("oauth-client-credentials")
                  .Parameters(parameters => parameters
                      .Body(b => b.Setup(body))
                      .Header(header => header.Setup("upvest-client-id", upvestClientId))
                      .Header(header => header.Setup("idempotency-key", idempotencyKey))
                      .Header(header => header.Setup("Content-Type", "application/json"))
                      .Header(header => header.Setup("upvest-api-version", (upvestApiVersion.HasValue) ? CoreHelper.JsonSerialize(upvestApiVersion.Value).Trim('\"') : "1"))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Bad Request. The incoming request had a malformed parameter/object.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("401", CreateErrorCase("Unauthorized. The caller has not been authenticated.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("403", CreateErrorCase("Forbidden. The caller has been authenticated but is not allowed to take the requested action.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Not Found. The requested resource could not be found.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("406", CreateErrorCase("Not Acceptable. The resource does not have a current representation that would be acceptable to the user agent. \"Accept\" header defined unsupported value.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("429", CreateErrorCase("Too Many Requests. The caller has exceeded their quota for the time period and has been throttled.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("500", CreateErrorCase("Internal Server Error. The service encountered an unexpected error.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("503", CreateErrorCase("Service Unavailable. The service handling for this request cannot be reached at this time.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("504", CreateErrorCase("Gateway Timeout. The service gateway has reached its internal timeout.", (errorReason, context) => new ErrorException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Returns the tax exemption specified by its ID.
        /// </summary>
        /// <param name="taxExemptionId">Required parameter: The unique identifier of the tax exemption. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestClientId">Required parameter: Your client ID, issued by Upvest. Identifies the client making the request. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestApiVersion">Optional parameter: Upvest API version (Note: Do not include quotation marks).</param>
        /// <returns>Returns the ApiResponse of Models.WebhookTaxExemptionCreatedTaxExemption response from the API call.</returns>
        public ApiResponse<Models.WebhookTaxExemptionCreatedTaxExemption> RetrieveTaxExemptionById(
                Guid taxExemptionId,
                Guid upvestClientId,
                Models.UpvestApiVersion? upvestApiVersion = Models.UpvestApiVersion.Enum1)
            => CoreHelper.RunTask(RetrieveTaxExemptionByIdAsync(taxExemptionId, upvestClientId, upvestApiVersion));

        /// <summary>
        /// Returns the tax exemption specified by its ID.
        /// </summary>
        /// <param name="taxExemptionId">Required parameter: The unique identifier of the tax exemption. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestClientId">Required parameter: Your client ID, issued by Upvest. Identifies the client making the request. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestApiVersion">Optional parameter: Upvest API version (Note: Do not include quotation marks).</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.WebhookTaxExemptionCreatedTaxExemption response from the API call.</returns>
        public async Task<ApiResponse<Models.WebhookTaxExemptionCreatedTaxExemption>> RetrieveTaxExemptionByIdAsync(
                Guid taxExemptionId,
                Guid upvestClientId,
                Models.UpvestApiVersion? upvestApiVersion = Models.UpvestApiVersion.Enum1,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.WebhookTaxExemptionCreatedTaxExemption>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/tax_exemptions/{tax_exemption_id}")
                  .WithAuth("oauth-client-credentials")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("tax_exemption_id", taxExemptionId))
                      .Header(header => header.Setup("upvest-client-id", upvestClientId))
                      .Header(header => header.Setup("upvest-api-version", (upvestApiVersion.HasValue) ? CoreHelper.JsonSerialize(upvestApiVersion.Value).Trim('\"') : "1"))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("401", CreateErrorCase("Unauthorized. The caller has not been authenticated.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("403", CreateErrorCase("Forbidden. The caller has been authenticated but is not allowed to take the requested action.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Not Found. The requested resource could not be found.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("406", CreateErrorCase("Not Acceptable. The resource does not have a current representation that would be acceptable to the user agent. \"Accept\" header defined unsupported value.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("429", CreateErrorCase("Too Many Requests. The caller has exceeded their quota for the time period and has been throttled.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("500", CreateErrorCase("Internal Server Error. The service encountered an unexpected error.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("503", CreateErrorCase("Service Unavailable. The service handling for this request cannot be reached at this time.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("504", CreateErrorCase("Gateway Timeout. The service gateway has reached its internal timeout.", (errorReason, context) => new ErrorException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Updates a tax exemption specified by its ID.
        /// </summary>
        /// <param name="taxExemptionId">Required parameter: The unique identifier of the tax exemption. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestClientId">Required parameter: Your client ID, issued by Upvest. Identifies the client making the request. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestApiVersion">Optional parameter: Upvest API version (Note: Do not include quotation marks).</param>
        /// <param name="body">Optional parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.TaxExemptionsUpdateResponse response from the API call.</returns>
        public ApiResponse<Models.TaxExemptionsUpdateResponse> UpdateTaxExemption(
                Guid taxExemptionId,
                Guid upvestClientId,
                Models.UpvestApiVersion? upvestApiVersion = Models.UpvestApiVersion.Enum1,
                Models.TaxesTaxExemptionsUpdateRequest body = null)
            => CoreHelper.RunTask(UpdateTaxExemptionAsync(taxExemptionId, upvestClientId, upvestApiVersion, body));

        /// <summary>
        /// Updates a tax exemption specified by its ID.
        /// </summary>
        /// <param name="taxExemptionId">Required parameter: The unique identifier of the tax exemption. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestClientId">Required parameter: Your client ID, issued by Upvest. Identifies the client making the request. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestApiVersion">Optional parameter: Upvest API version (Note: Do not include quotation marks).</param>
        /// <param name="body">Optional parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.TaxExemptionsUpdateResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.TaxExemptionsUpdateResponse>> UpdateTaxExemptionAsync(
                Guid taxExemptionId,
                Guid upvestClientId,
                Models.UpvestApiVersion? upvestApiVersion = Models.UpvestApiVersion.Enum1,
                Models.TaxesTaxExemptionsUpdateRequest body = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.TaxExemptionsUpdateResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Put, "/tax_exemptions/{tax_exemption_id}")
                  .WithAuth("oauth-client-credentials")
                  .Parameters(parameters => parameters
                      .Body(b => b.Setup(body))
                      .Template(template => template.Setup("tax_exemption_id", taxExemptionId))
                      .Header(header => header.Setup("upvest-client-id", upvestClientId))
                      .Header(header => header.Setup("Content-Type", "application/json"))
                      .Header(header => header.Setup("upvest-api-version", (upvestApiVersion.HasValue) ? CoreHelper.JsonSerialize(upvestApiVersion.Value).Trim('\"') : "1"))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Bad Request. The incoming request had a malformed parameter/object.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("401", CreateErrorCase("Unauthorized. The caller has not been authenticated.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("403", CreateErrorCase("Forbidden. The caller has been authenticated but is not allowed to take the requested action.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Not Found. The requested resource could not be found.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("406", CreateErrorCase("Not Acceptable. The resource does not have a current representation that would be acceptable to the user agent. \"Accept\" header defined unsupported value.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("429", CreateErrorCase("Too Many Requests. The caller has exceeded their quota for the time period and has been throttled.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("500", CreateErrorCase("Internal Server Error. The service encountered an unexpected error.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("503", CreateErrorCase("Service Unavailable. The service handling for this request cannot be reached at this time.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("504", CreateErrorCase("Gateway Timeout. The service gateway has reached its internal timeout.", (errorReason, context) => new ErrorException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Deletes a tax exemption specified by its ID.
        /// </summary>
        /// <param name="taxExemptionId">Required parameter: The unique identifier of the tax exemption. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestClientId">Required parameter: Your client ID, issued by Upvest. Identifies the client making the request. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestApiVersion">Optional parameter: Upvest API version (Note: Do not include quotation marks).</param>
        public void DeleteTaxExemption(
                Guid taxExemptionId,
                Guid upvestClientId,
                Models.UpvestApiVersion? upvestApiVersion = Models.UpvestApiVersion.Enum1)
            => CoreHelper.RunVoidTask(DeleteTaxExemptionAsync(taxExemptionId, upvestClientId, upvestApiVersion));

        /// <summary>
        /// Deletes a tax exemption specified by its ID.
        /// </summary>
        /// <param name="taxExemptionId">Required parameter: The unique identifier of the tax exemption. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestClientId">Required parameter: Your client ID, issued by Upvest. Identifies the client making the request. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestApiVersion">Optional parameter: Upvest API version (Note: Do not include quotation marks).</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the void response from the API call.</returns>
        public async Task DeleteTaxExemptionAsync(
                Guid taxExemptionId,
                Guid upvestClientId,
                Models.UpvestApiVersion? upvestApiVersion = Models.UpvestApiVersion.Enum1,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<VoidType>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Delete, "/tax_exemptions/{tax_exemption_id}")
                  .WithAuth("oauth-client-credentials")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("tax_exemption_id", taxExemptionId))
                      .Header(header => header.Setup("upvest-client-id", upvestClientId))
                      .Header(header => header.Setup("upvest-api-version", (upvestApiVersion.HasValue) ? CoreHelper.JsonSerialize(upvestApiVersion.Value).Trim('\"') : "1"))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("401", CreateErrorCase("Unauthorized. The caller has not been authenticated.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("403", CreateErrorCase("Forbidden. The caller has been authenticated but is not allowed to take the requested action.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Not Found. The requested resource could not be found.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("406", CreateErrorCase("Not Acceptable. The resource does not have a current representation that would be acceptable to the user agent. \"Accept\" header defined unsupported value.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("429", CreateErrorCase("Too Many Requests. The caller has exceeded their quota for the time period and has been throttled.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("500", CreateErrorCase("Internal Server Error. The service encountered an unexpected error.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("503", CreateErrorCase("Service Unavailable. The service handling for this request cannot be reached at this time.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("504", CreateErrorCase("Gateway Timeout. The service gateway has reached its internal timeout.", (errorReason, context) => new ErrorException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Returns the tax exemptions of the user specified by ID.
        /// </summary>
        /// <param name="userId">Required parameter: The unique identifier of the user. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestClientId">Required parameter: Your client ID, issued by Upvest. Identifies the client making the request. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestApiVersion">Optional parameter: Upvest API version (Note: Do not include quotation marks).</param>
        /// <param name="sort">Optional parameter: Sort the result by `created_at`..</param>
        /// <param name="order">Optional parameter: Sort order of the result list if the `sort` parameter is specified. Use `ASC` for ascending or `DESC` for descending sort order..</param>
        /// <param name="offset">Optional parameter: Use the `offset` argument to specify where in the list of results to start when returning items for a particular query..</param>
        /// <param name="limit">Optional parameter: Use the `limit` argument to specify the maximum number of items returned..</param>
        /// <returns>Returns the ApiResponse of Models.TaxExemptionRetrieveForUserResponse response from the API call.</returns>
        public ApiResponse<Models.TaxExemptionRetrieveForUserResponse> RetrieveTaxExemptionsForUser(
                Guid userId,
                Guid upvestClientId,
                Models.UpvestApiVersion? upvestApiVersion = Models.UpvestApiVersion.Enum1,
                Models.Sort9? sort = Models.Sort9.CreatedAt,
                Models.Order? order = Models.Order.Asc,
                int? offset = null,
                int? limit = 100)
            => CoreHelper.RunTask(RetrieveTaxExemptionsForUserAsync(userId, upvestClientId, upvestApiVersion, sort, order, offset, limit));

        /// <summary>
        /// Returns the tax exemptions of the user specified by ID.
        /// </summary>
        /// <param name="userId">Required parameter: The unique identifier of the user. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestClientId">Required parameter: Your client ID, issued by Upvest. Identifies the client making the request. Universally Unique Identifier (UUID)..</param>
        /// <param name="upvestApiVersion">Optional parameter: Upvest API version (Note: Do not include quotation marks).</param>
        /// <param name="sort">Optional parameter: Sort the result by `created_at`..</param>
        /// <param name="order">Optional parameter: Sort order of the result list if the `sort` parameter is specified. Use `ASC` for ascending or `DESC` for descending sort order..</param>
        /// <param name="offset">Optional parameter: Use the `offset` argument to specify where in the list of results to start when returning items for a particular query..</param>
        /// <param name="limit">Optional parameter: Use the `limit` argument to specify the maximum number of items returned..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.TaxExemptionRetrieveForUserResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.TaxExemptionRetrieveForUserResponse>> RetrieveTaxExemptionsForUserAsync(
                Guid userId,
                Guid upvestClientId,
                Models.UpvestApiVersion? upvestApiVersion = Models.UpvestApiVersion.Enum1,
                Models.Sort9? sort = Models.Sort9.CreatedAt,
                Models.Order? order = Models.Order.Asc,
                int? offset = null,
                int? limit = 100,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.TaxExemptionRetrieveForUserResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/users/{user_id}/tax_exemptions")
                  .WithAuth("oauth-client-credentials")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("user_id", userId))
                      .Header(header => header.Setup("upvest-client-id", upvestClientId))
                      .Header(header => header.Setup("upvest-api-version", (upvestApiVersion.HasValue) ? CoreHelper.JsonSerialize(upvestApiVersion.Value).Trim('\"') : "1"))
                      .Query(query => query.Setup("sort", (sort.HasValue) ? CoreHelper.JsonSerialize(sort.Value).Trim('\"') : "created_at"))
                      .Query(query => query.Setup("order", (order.HasValue) ? CoreHelper.JsonSerialize(order.Value).Trim('\"') : "ASC"))
                      .Query(query => query.Setup("offset", offset))
                      .Query(query => query.Setup("limit", limit ?? 100))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Bad Request. The incoming request had a malformed parameter/object.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("401", CreateErrorCase("Unauthorized. The caller has not been authenticated.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("403", CreateErrorCase("Forbidden. The caller has been authenticated but is not allowed to take the requested action.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Not Found. The requested resource could not be found.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("405", CreateErrorCase("Method Not Allowed. The requested method is not allowed on the requested resource.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("406", CreateErrorCase("Not Acceptable. The resource does not have a current representation that would be acceptable to the user agent. \"Accept\" header defined unsupported value.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("429", CreateErrorCase("Too Many Requests. The caller has exceeded their quota for the time period and has been throttled.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("500", CreateErrorCase("Internal Server Error. The service encountered an unexpected error.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("503", CreateErrorCase("Service Unavailable. The service handling for this request cannot be reached at this time.", (errorReason, context) => new ErrorException(errorReason, context)))
                  .ErrorCase("504", CreateErrorCase("Gateway Timeout. The service gateway has reached its internal timeout.", (errorReason, context) => new ErrorException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}