// <copyright file="AbsoluteFee.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using UpvestInvestmentApi.Standard.Utilities;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// AbsoluteFee.
    /// </summary>
    public class AbsoluteFee
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AbsoluteFee"/> class.
        /// </summary>
        public AbsoluteFee()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AbsoluteFee"/> class.
        /// </summary>
        /// <param name="type">type.</param>
        /// <param name="valueType">value_type.</param>
        /// <param name="chargeMethod">charge_method.</param>
        /// <param name="cashAmount">cash_amount.</param>
        /// <param name="currency">currency.</param>
        public AbsoluteFee(
            Models.FeeType type,
            string valueType,
            Models.FeeChargeMethod chargeMethod,
            string cashAmount,
            Models.Currency29 currency)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Type = type;
            this.ValueType = valueType;
            this.ChargeMethod = chargeMethod;
            this.CashAmount = cashAmount;
            this.Currency = currency;
        }

        /// <summary>
        /// Fee type
        /// * TRANSACTION_FEE_BUY -
        /// * TRANSACTION_FEE_SELL -
        /// </summary>
        [JsonProperty("type")]
        [JsonRequired]
        public Models.FeeType Type { get; set; }

        /// <summary>
        /// The value type must be “ABSOLUTE”.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("value_type")]
        [JsonRequired]
        public string ValueType { get; set; }

        /// <summary>
        /// Indicates whether the fee will be charged by client or by other methods.
        /// * CHARGED_BY_CLIENT -
        /// * COLLECTED_BY_UPVEST -
        /// </summary>
        [JsonProperty("charge_method")]
        [JsonRequired]
        public Models.FeeChargeMethod ChargeMethod { get; set; }

        /// <summary>
        /// A positive cash amount, as a decimal string with up to two decimal places.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("cash_amount")]
        [JsonRequired]
        public string CashAmount { get; set; }

        /// <summary>
        /// Alphabetic three-letter [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) currency code.
        /// * EUR - Euro
        /// * GBP - British Pound
        /// * USD - US Dollar
        /// </summary>
        [JsonProperty("currency")]
        [JsonRequired]
        public Models.Currency29 Currency { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AbsoluteFee : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Type = {this.Type}");
            toStringOutput.Add($"ValueType = {this.ValueType ?? "null"}");
            toStringOutput.Add($"ChargeMethod = {this.ChargeMethod}");
            toStringOutput.Add($"CashAmount = {this.CashAmount ?? "null"}");
            toStringOutput.Add($"Currency = {this.Currency}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}