// <copyright file="Account.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// Account.
    /// </summary>
    public class Account
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Account"/> class.
        /// </summary>
        public Account()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Account"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="createdAt">created_at.</param>
        /// <param name="updatedAt">updated_at.</param>
        /// <param name="accountGroupId">account_group_id.</param>
        /// <param name="type">type.</param>
        /// <param name="users">users.</param>
        /// <param name="accountNumber">account_number.</param>
        /// <param name="name">name.</param>
        /// <param name="status">status.</param>
        public Account(
            Guid id,
            DateTime createdAt,
            DateTime updatedAt,
            Guid accountGroupId,
            Models.Type16 type,
            List<Models.User> users,
            int accountNumber,
            string name,
            Models.Status21 status)
        {
            this.Id = id;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.AccountGroupId = accountGroupId;
            this.Type = type;
            this.Users = users;
            this.AccountNumber = accountNumber;
            this.Name = name;
            this.Status = status;
        }

        /// <summary>
        /// Universally Unique Identifier (UUID) of the account.
        /// </summary>
        [JsonProperty("id")]
        [JsonRequired]
        public Guid Id { get; set; }

        /// <summary>
        /// Date and time when the resource was created. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("created_at")]
        [JsonRequired]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Date and time when the resource was last updated. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("updated_at")]
        [JsonRequired]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Universally Unique Identifier (UUID) of the account group.
        /// </summary>
        [JsonProperty("account_group_id")]
        [JsonRequired]
        public Guid AccountGroupId { get; set; }

        /// <summary>
        /// Account type.
        /// * TRADING - Orders in accounts of this type are created on a specific instrument basis.
        /// * PORTFOLIO - Orders in accounts of this type are created on a portfolio basis and additional portfolio functionality is available.
        /// </summary>
        [JsonProperty("type")]
        [JsonRequired]
        public Models.Type16 Type { get; set; }

        /// <summary>
        /// The users associated with the account, each with their relation type.
        /// </summary>
        [JsonProperty("users")]
        [JsonRequired]
        public List<Models.User> Users { get; set; }

        /// <summary>
        /// The serial account number of the account in the account group.
        /// </summary>
        [JsonProperty("account_number")]
        [JsonRequired]
        public int AccountNumber { get; set; }

        /// <summary>
        /// The name of the account.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("name")]
        [JsonRequired]
        public string Name { get; set; }

        /// <summary>
        /// The status of the account.
        /// * `PENDING_APPROVAL` — Account approval is pending — the account is visible through our API but cannot be acted on.
        /// * `ACTIVE` — Account is active — full functionality of the Investment API is accessible.
        /// * `CLOSING` — Account is closing — only sell orders or the transfer of positions out are permissible before the account is closed.
        /// * `CLOSED` — Account is closed with zero balance.
        /// * `LOCKED` — Account is locked for all actions.
        /// </summary>
        [JsonProperty("status")]
        [JsonRequired]
        public Models.Status21 Status { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Account : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {this.Id}");
            toStringOutput.Add($"CreatedAt = {this.CreatedAt}");
            toStringOutput.Add($"UpdatedAt = {this.UpdatedAt}");
            toStringOutput.Add($"AccountGroupId = {this.AccountGroupId}");
            toStringOutput.Add($"Type = {this.Type}");
            toStringOutput.Add($"Users = {(this.Users == null ? "null" : $"[{string.Join(", ", this.Users)} ]")}");
            toStringOutput.Add($"AccountNumber = {this.AccountNumber}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"Status = {this.Status}");
        }
    }
}