// <copyright file="AccountCreateBusinessRequest.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using UpvestInvestmentApi.Standard.Utilities;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// AccountCreateBusinessRequest.
    /// </summary>
    public class AccountCreateBusinessRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountCreateBusinessRequest"/> class.
        /// </summary>
        public AccountCreateBusinessRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountCreateBusinessRequest"/> class.
        /// </summary>
        /// <param name="businessId">business_id.</param>
        /// <param name="accountGroupId">account_group_id.</param>
        /// <param name="type">type.</param>
        /// <param name="name">name.</param>
        public AccountCreateBusinessRequest(
            Guid businessId,
            Guid accountGroupId,
            Models.Type16 type,
            string name = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.BusinessId = businessId;
            this.AccountGroupId = accountGroupId;
            this.Type = type;
            this.Name = name;
        }

        /// <summary>
        /// Unique identifier for the business.
        /// </summary>
        [JsonProperty("business_id")]
        [JsonRequired]
        public Guid BusinessId { get; set; }

        /// <summary>
        /// Account group unique identifier.
        /// </summary>
        [JsonProperty("account_group_id")]
        [JsonRequired]
        public Guid AccountGroupId { get; set; }

        /// <summary>
        /// Account type.
        /// * TRADING - Orders in accounts of this type are created on a specific instrument basis.
        /// * PORTFOLIO - Orders in accounts of this type are created on a portfolio basis and additional portfolio functionality is available.
        /// </summary>
        [JsonProperty("type")]
        [JsonRequired]
        public Models.Type16 Type { get; set; }

        /// <summary>
        /// The name of the account.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AccountCreateBusinessRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"BusinessId = {this.BusinessId}");
            toStringOutput.Add($"AccountGroupId = {this.AccountGroupId}");
            toStringOutput.Add($"Type = {this.Type}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}