// <copyright file="Account15.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// Account15.
    /// </summary>
    public class Account15
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Account15"/> class.
        /// </summary>
        public Account15()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Account15"/> class.
        /// </summary>
        /// <param name="iban">iban.</param>
        public Account15(
            string iban)
        {
            this.Iban = iban;
        }

        /// <summary>
        /// International Bank Account Number [IBAN](https://en.wikipedia.org/wiki/International_Bank_Account_Number).
        /// </summary>
        [JsonProperty("iban")]
        public string Iban { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Account15 : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Iban = {this.Iban ?? "null"}");
        }
    }
}