// <copyright file="BaseAmountScope.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// BaseAmountScope.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum BaseAmountScope
    {
        /// <summary>
        /// GrossAmount.
        /// </summary>
        [EnumMember(Value = "GROSS_AMOUNT")]
        GrossAmount,

        /// <summary>
        /// Order.
        /// </summary>
        [EnumMember(Value = "ORDER")]
        Order
    }
}