// <copyright file="BusinessCompanyCreateResponse.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using UpvestInvestmentApi.Standard.Utilities;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// BusinessCompanyCreateResponse.
    /// </summary>
    public class BusinessCompanyCreateResponse
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessCompanyCreateResponse"/> class.
        /// </summary>
        public BusinessCompanyCreateResponse()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessCompanyCreateResponse"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="createdAt">created_at.</param>
        /// <param name="updatedAt">updated_at.</param>
        /// <param name="contactEmail">contact_email.</param>
        /// <param name="registeredAddress">registered_address.</param>
        /// <param name="registrationNumber">registration_number.</param>
        /// <param name="taxInformation">tax_information.</param>
        /// <param name="businessType">business_type.</param>
        /// <param name="identification">identification.</param>
        /// <param name="termsAndConditions">terms_and_conditions.</param>
        /// <param name="dataPrivacyAndSharingAgreement">data_privacy_and_sharing_agreement.</param>
        /// <param name="status">status.</param>
        public BusinessCompanyCreateResponse(
            Guid? id = null,
            DateTime? createdAt = null,
            DateTime? updatedAt = null,
            string contactEmail = null,
            Models.Address registeredAddress = null,
            string registrationNumber = null,
            Models.TaxInformation taxInformation = null,
            Models.BusinessType? businessType = null,
            Models.Identification8 identification = null,
            Models.TermsAndConditions4 termsAndConditions = null,
            Models.DataPrivacyAndSharingAgreement4 dataPrivacyAndSharingAgreement = null,
            Models.Status99? status = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Id = id;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.ContactEmail = contactEmail;
            this.RegisteredAddress = registeredAddress;
            this.RegistrationNumber = registrationNumber;
            this.TaxInformation = taxInformation;
            this.BusinessType = businessType;
            this.Identification = identification;
            this.TermsAndConditions = termsAndConditions;
            this.DataPrivacyAndSharingAgreement = dataPrivacyAndSharingAgreement;
            this.Status = status;
        }

        /// <summary>
        /// Unique identifier for the business.
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public Guid? Id { get; set; }

        /// <summary>
        /// Date and time when the resource was created. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("created_at", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? CreatedAt { get; set; }

        /// <summary>
        /// Date and time when the resource was last updated. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("updated_at", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? UpdatedAt { get; set; }

        /// <summary>
        /// Contact email address of the business.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("contact_email", NullValueHandling = NullValueHandling.Ignore)]
        public string ContactEmail { get; set; }

        /// <summary>
        /// Address. Must not be a P.O. box or c/o address.
        /// </summary>
        [JsonProperty("registered_address", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Address RegisteredAddress { get; set; }

        /// <summary>
        /// Registration number of the business.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("registration_number", NullValueHandling = NullValueHandling.Ignore)]
        public string RegistrationNumber { get; set; }

        /// <summary>
        /// Tax information of the business.
        /// </summary>
        [JsonProperty("tax_information", NullValueHandling = NullValueHandling.Ignore)]
        public Models.TaxInformation TaxInformation { get; set; }

        /// <summary>
        /// Type of the business.
        /// </summary>
        [JsonProperty("business_type", NullValueHandling = NullValueHandling.Ignore)]
        public Models.BusinessType? BusinessType { get; set; }

        /// <summary>
        /// Identification information of the business.
        /// </summary>
        [JsonProperty("identification", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Identification8 Identification { get; set; }

        /// <summary>
        /// Terms and conditions agreement.
        /// </summary>
        [JsonProperty("terms_and_conditions", NullValueHandling = NullValueHandling.Ignore)]
        public Models.TermsAndConditions4 TermsAndConditions { get; set; }

        /// <summary>
        /// Data privacy and sharing agreement.
        /// </summary>
        [JsonProperty("data_privacy_and_sharing_agreement", NullValueHandling = NullValueHandling.Ignore)]
        public Models.DataPrivacyAndSharingAgreement4 DataPrivacyAndSharingAgreement { get; set; }

        /// <summary>
        /// Status of the business.
        /// * ACTIVE -
        /// * INACTIVE -
        /// * OFFBOARDING -
        /// * OFFBOARDED -
        /// </summary>
        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Status99? Status { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"BusinessCompanyCreateResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {(this.Id == null ? "null" : this.Id.ToString())}");
            toStringOutput.Add($"CreatedAt = {(this.CreatedAt == null ? "null" : this.CreatedAt.ToString())}");
            toStringOutput.Add($"UpdatedAt = {(this.UpdatedAt == null ? "null" : this.UpdatedAt.ToString())}");
            toStringOutput.Add($"ContactEmail = {this.ContactEmail ?? "null"}");
            toStringOutput.Add($"RegisteredAddress = {(this.RegisteredAddress == null ? "null" : this.RegisteredAddress.ToString())}");
            toStringOutput.Add($"RegistrationNumber = {this.RegistrationNumber ?? "null"}");
            toStringOutput.Add($"TaxInformation = {(this.TaxInformation == null ? "null" : this.TaxInformation.ToString())}");
            toStringOutput.Add($"BusinessType = {(this.BusinessType == null ? "null" : this.BusinessType.ToString())}");
            toStringOutput.Add($"Identification = {(this.Identification == null ? "null" : this.Identification.ToString())}");
            toStringOutput.Add($"TermsAndConditions = {(this.TermsAndConditions == null ? "null" : this.TermsAndConditions.ToString())}");
            toStringOutput.Add($"DataPrivacyAndSharingAgreement = {(this.DataPrivacyAndSharingAgreement == null ? "null" : this.DataPrivacyAndSharingAgreement.ToString())}");
            toStringOutput.Add($"Status = {(this.Status == null ? "null" : this.Status.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}