// <copyright file="BusinessReport.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using UpvestInvestmentApi.Standard.Utilities;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// BusinessReport.
    /// </summary>
    public class BusinessReport
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessReport"/> class.
        /// </summary>
        public BusinessReport()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessReport"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="createdAt">created_at.</param>
        /// <param name="businessId">business_id.</param>
        /// <param name="type">type.</param>
        /// <param name="substitutedReportId">substituted_report_id.</param>
        /// <param name="data">data.</param>
        public BusinessReport(
            Guid id,
            DateTime createdAt,
            Guid businessId,
            Models.ReportType type,
            Guid? substitutedReportId = null,
            Models.ReportData data = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Id = id;
            this.CreatedAt = createdAt;
            this.BusinessId = businessId;
            this.Type = type;
            this.SubstitutedReportId = substitutedReportId;
            this.Data = data;
        }

        /// <summary>
        /// The unique identifier of the report, as a UUID.
        /// </summary>
        [JsonProperty("id")]
        [JsonRequired]
        public Guid Id { get; set; }

        /// <summary>
        /// Date and time when the resource was created. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("created_at")]
        [JsonRequired]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Unique identifier for the business.
        /// </summary>
        [JsonProperty("business_id")]
        [JsonRequired]
        public Guid BusinessId { get; set; }

        /// <summary>
        /// Report type
        /// * ACCOUNT_CLOSING - Securities account closure
        /// * ACCOUNT_OPENING - Securities account opening
        /// * AD_HOC_ACCOUNT_STATEMENT - Ad hoc account statement
        /// * ANNUAL_INCOME_STATEMENT - Annual tax income statement ("Erträgnisaufstellung")
        /// * ANNUAL_TAX_STATEMENT - Annual tax reporting
        /// * BANK_ACCOUNT_CONNECTED - Connect reference bank account
        /// * BUY_ORDER - Buy order
        /// * CANCELLED_ORDER - Cancelled buy or sell order (not yet executed, user cancels or trading venue cancelled)
        /// * CORPORATE_ACTION_CASH_TRANSACTION - cash transaction document (after corporate action)
        /// * CORPORATE_ACTION_SECURITY_TRANSACTION - security transaction document (after corporate action)
        /// * DIRECT_DEBIT_MANDATE - Creation of SEPA direct debit mandate
        /// * EX_POST_COST - Ex-post cost report
        /// * FEE_COLLECTION - Intake of service fees
        /// * FRENCH_IFU - French tax statement (Imprimé fiscal unique)
        /// * GENERIC_COMMUNICATION - Generic communication
        /// * INCOME_DISTRIBUTION - Income distribution report
        /// * LOSS_THRESHOLD - Notification that a holding has depreciated by 10%, or a multiple thereof, against its purchase value
        /// * MONTHLY_BILLING_STATEMENT - Monthly billing activities statement
        /// * ORDER_EX_ANTE_COST - Ex-ante cost report for a single order
        /// * ORDER_EX_ANTE_COST_SAVINGS_PLAN - Ex-ante cost report for a savings plan order
        /// * QUARTERLY_ACCOUNT_STATEMENT - Quarterly account statement
        /// * REVOKED_ORDER - Revoked buy or sell order ("Storno")
        /// * SECURITIES_TRANSFER_INCOMING - Securities are transferred in
        /// * SECURITIES_TRANSFER_OUTGOING - Securities are being transferred out
        /// * SELL_ORDER - Sell order
        /// * TAX_CONSOLIDATED_CERTIFICATE_UK - UK Consolidated Tax Certificate
        /// * TAX_PAYMENT - Tax payment document
        /// * TAX_PREPAYMENT_DE - German tax prepayment (Vorabpauschale)
        /// * TAX_PREPAYMENT_DE_CANCELLATION - German tax prepayment (Vorabpauschale) cancellation
        /// * TAX_REFUND - Tax refund document (after tax optimization)
        /// </summary>
        [JsonProperty("type")]
        [JsonRequired]
        public Models.ReportType Type { get; set; }

        /// <summary>
        /// The unique identifier of the report that this report replaces, as a UUID. Populated when a mistrade causes a corrected report to be issued; `null` otherwise.
        /// </summary>
        [JsonProperty("substituted_report_id", NullValueHandling = NullValueHandling.Include)]
        public Guid? SubstitutedReportId { get; set; }

        /// <summary>
        /// The contents of a report, including the account it relates to and references to the resources that triggered it.
        /// </summary>
        [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ReportData Data { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"BusinessReport : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {this.Id}");
            toStringOutput.Add($"CreatedAt = {this.CreatedAt}");
            toStringOutput.Add($"BusinessId = {this.BusinessId}");
            toStringOutput.Add($"Type = {this.Type}");
            toStringOutput.Add($"SubstitutedReportId = {(this.SubstitutedReportId == null ? "null" : this.SubstitutedReportId.ToString())}");
            toStringOutput.Add($"Data = {(this.Data == null ? "null" : this.Data.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}