// <copyright file="BusinessCheckKyb.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using UpvestInvestmentApi.Standard.Utilities;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// BusinessCheckKyb.
    /// </summary>
    public class BusinessCheckKyb
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessCheckKyb"/> class.
        /// </summary>
        public BusinessCheckKyb()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessCheckKyb"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="businessId">business_id.</param>
        /// <param name="type">type.</param>
        /// <param name="originallyConfirmedAt">originally_confirmed_at.</param>
        /// <param name="checkConfirmedAt">check_confirmed_at.</param>
        /// <param name="status">status.</param>
        /// <param name="dataDownloadLink">data_download_link.</param>
        /// <param name="documentType">document_type.</param>
        public BusinessCheckKyb(
            Guid id,
            Guid businessId,
            string type,
            DateTime originallyConfirmedAt,
            DateTime checkConfirmedAt,
            Models.Status109 status,
            string dataDownloadLink,
            string documentType)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Id = id;
            this.BusinessId = businessId;
            this.Type = type;
            this.OriginallyConfirmedAt = originallyConfirmedAt;
            this.CheckConfirmedAt = checkConfirmedAt;
            this.Status = status;
            this.DataDownloadLink = dataDownloadLink;
            this.DocumentType = documentType;
        }

        /// <summary>
        /// Business Check unique identifier.
        /// </summary>
        [JsonProperty("id")]
        [JsonRequired]
        public Guid Id { get; set; }

        /// <summary>
        /// Unique identifier for the business.
        /// </summary>
        [JsonProperty("business_id")]
        [JsonRequired]
        public Guid BusinessId { get; set; }

        /// <summary>
        /// The type of check must be “KYB”.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("type")]
        [JsonRequired]
        public string Type { get; set; }

        /// <summary>
        /// The date and time when the check was first confirmed. When the check has only been confirmed once, this value is the same as check_confirmed_at. When renewing KYB check, this value remains the same as when the check was first confirmed.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("originally_confirmed_at")]
        [JsonRequired]
        public DateTime OriginallyConfirmedAt { get; set; }

        /// <summary>
        /// The date and time when the check was latest confirmed
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("check_confirmed_at")]
        [JsonRequired]
        public DateTime CheckConfirmedAt { get; set; }

        /// <summary>
        /// Final status of the business check.
        /// * IN_PROGRESS - Check is in progress
        /// * PASSED - Check passed
        /// * FAILED - Check failed
        /// </summary>
        [JsonProperty("status")]
        [JsonRequired]
        public Models.Status109 Status { get; set; }

        /// <summary>
        /// Link to download the document bundle submitted for the KYB check
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("data_download_link")]
        [JsonRequired]
        public string DataDownloadLink { get; set; }

        /// <summary>
        /// Type of the document bundle. Always `KYB_DOCUMENTS`
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("document_type")]
        [JsonRequired]
        public string DocumentType { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"BusinessCheckKyb : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {this.Id}");
            toStringOutput.Add($"BusinessId = {this.BusinessId}");
            toStringOutput.Add($"Type = {this.Type ?? "null"}");
            toStringOutput.Add($"OriginallyConfirmedAt = {this.OriginallyConfirmedAt}");
            toStringOutput.Add($"CheckConfirmedAt = {this.CheckConfirmedAt}");
            toStringOutput.Add($"Status = {this.Status}");
            toStringOutput.Add($"DataDownloadLink = {this.DataDownloadLink ?? "null"}");
            toStringOutput.Add($"DocumentType = {this.DocumentType ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}