// <copyright file="BusinessType.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// BusinessType.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum BusinessType
    {
        /// <summary>
        /// LimitedLiabilityCompany.
        /// </summary>
        [EnumMember(Value = "LIMITED_LIABILITY_COMPANY")]
        LimitedLiabilityCompany
    }
}