// <copyright file="CancellationReasonCode.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// CancellationReasonCode.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum CancellationReasonCode
    {
        /// <summary>
        /// AccountIsEmpty.
        /// </summary>
        [EnumMember(Value = "ACCOUNT_IS_EMPTY")]
        AccountIsEmpty,

        /// <summary>
        /// CancelledByClient.
        /// </summary>
        [EnumMember(Value = "CANCELLED_BY_CLIENT")]
        CancelledByClient,

        /// <summary>
        /// CancelledByUpvest.
        /// </summary>
        [EnumMember(Value = "CANCELLED_BY_UPVEST")]
        CancelledByUpvest,

        /// <summary>
        /// PortfolioIsBalanced.
        /// </summary>
        [EnumMember(Value = "PORTFOLIO_IS_BALANCED")]
        PortfolioIsBalanced,

        /// <summary>
        /// SellLimitExceeded.
        /// </summary>
        [EnumMember(Value = "SELL_LIMIT_EXCEEDED")]
        SellLimitExceeded
    }
}