// <copyright file="CashBalancesRetrieveResponse.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// CashBalancesRetrieveResponse.
    /// </summary>
    public class CashBalancesRetrieveResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CashBalancesRetrieveResponse"/> class.
        /// </summary>
        public CashBalancesRetrieveResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CashBalancesRetrieveResponse"/> class.
        /// </summary>
        /// <param name="meta">meta.</param>
        /// <param name="data">data.</param>
        public CashBalancesRetrieveResponse(
            Models.Meta meta,
            List<Models.Datum> data)
        {
            this.Meta = meta;
            this.Data = data;
        }

        /// <summary>
        /// Offset/limit pagination metadata for a list response. Contains the `offset` and `limit` applied to the request, the `count` of resources returned in this page, and the `total_count` of matching resources.
        /// </summary>
        [JsonProperty("meta")]
        public Models.Meta Meta { get; set; }

        /// <summary>
        /// The list of cash balance objects, one per currency the account group holds.
        /// </summary>
        [JsonProperty("data")]
        public List<Models.Datum> Data { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CashBalancesRetrieveResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Meta = {(this.Meta == null ? "null" : this.Meta.ToString())}");
            toStringOutput.Add($"Data = {(this.Data == null ? "null" : $"[{string.Join(", ", this.Data)} ]")}");
        }
    }
}