// <copyright file="ClosureReason.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// ClosureReason.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ClosureReason
    {
        /// <summary>
        /// Dunning.
        /// </summary>
        [EnumMember(Value = "dunning")]
        Dunning,

        /// <summary>
        /// PowerOfAttorney.
        /// </summary>
        [EnumMember(Value = "power_of_attorney")]
        PowerOfAttorney,

        /// <summary>
        /// LossOfLegalCapacity.
        /// </summary>
        [EnumMember(Value = "loss_of_legal_capacity")]
        LossOfLegalCapacity,

        /// <summary>
        /// Aml.
        /// </summary>
        [EnumMember(Value = "aml")]
        Aml,

        /// <summary>
        /// RiskBased.
        /// </summary>
        [EnumMember(Value = "risk_based")]
        RiskBased,

        /// <summary>
        /// ContractBreach.
        /// </summary>
        [EnumMember(Value = "contract_breach")]
        ContractBreach,

        /// <summary>
        /// UserInitiated.
        /// </summary>
        [EnumMember(Value = "user_initiated")]
        UserInitiated
    }
}