// <copyright file="Datum7.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// Datum7.
    /// </summary>
    public class Datum7
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Datum7"/> class.
        /// </summary>
        public Datum7()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Datum7"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="createdAt">created_at.</param>
        /// <param name="updatedAt">updated_at.</param>
        /// <param name="name">name.</param>
        /// <param name="fractionalTrading">fractional_trading.</param>
        /// <param name="tradingStatus">trading_status.</param>
        /// <param name="isin">isin.</param>
        /// <param name="wkn">wkn.</param>
        /// <param name="details">details.</param>
        public Datum7(
            Guid id,
            DateTime createdAt,
            DateTime updatedAt,
            string name,
            bool fractionalTrading,
            Models.InstrumentTradingStatus tradingStatus,
            string isin = null,
            string wkn = null,
            Models.Details details = null)
        {
            this.Id = id;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.Isin = isin;
            this.Wkn = wkn;
            this.Name = name;
            this.FractionalTrading = fractionalTrading;
            this.TradingStatus = tradingStatus;
            this.Details = details;
        }

        /// <summary>
        /// Instrument unique identifier.
        /// </summary>
        [JsonProperty("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Date and time when the resource was created. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Date and time when the resource was last updated. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("updated_at")]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// International securities identification number defined by [ISO 6166](https://en.wikipedia.org/wiki/International_Securities_Identification_Number).
        /// </summary>
        [JsonProperty("isin", NullValueHandling = NullValueHandling.Ignore)]
        public string Isin { get; set; }

        /// <summary>
        /// German securities identification code known as [Wertpapierkennnummer](https://en.wikipedia.org/wiki/Wertpapierkennnummer).
        /// </summary>
        [JsonProperty("wkn", NullValueHandling = NullValueHandling.Ignore)]
        public string Wkn { get; set; }

        /// <summary>
        /// Instrument name
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// Determines whether the platform can handle fractional investments within this instrument.
        /// </summary>
        [JsonProperty("fractional_trading")]
        public bool FractionalTrading { get; set; }

        /// <summary>
        /// Instrument trading status
        /// * ACTIVE - The instrument can currently be traded on the Upvest platform.
        /// * INACTIVE - The instrument cannot currently be traded on the Upvest platform.
        /// </summary>
        [JsonProperty("trading_status")]
        public Models.InstrumentTradingStatus TradingStatus { get; set; }

        /// <summary>
        /// Details
        /// </summary>
        [JsonProperty("details", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Details Details { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Datum7 : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {this.Id}");
            toStringOutput.Add($"CreatedAt = {this.CreatedAt}");
            toStringOutput.Add($"UpdatedAt = {this.UpdatedAt}");
            toStringOutput.Add($"Isin = {this.Isin ?? "null"}");
            toStringOutput.Add($"Wkn = {this.Wkn ?? "null"}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"FractionalTrading = {this.FractionalTrading}");
            toStringOutput.Add($"TradingStatus = {this.TradingStatus}");
            toStringOutput.Add($"Details = {(this.Details == null ? "null" : this.Details.ToString())}");
        }
    }
}