// <copyright file="Datum4.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// Datum4.
    /// </summary>
    public class Datum4
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Datum4"/> class.
        /// </summary>
        public Datum4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Datum4"/> class.
        /// </summary>
        /// <param name="currency">currency.</param>
        /// <param name="owner">owner.</param>
        /// <param name="identification">identification.</param>
        /// <param name="virtualBankAccountId">virtual_bank_account_id.</param>
        /// <param name="name">name.</param>
        /// <param name="remittanceInformation">remittance_information.</param>
        public Datum4(
            Models.Currency currency,
            Models.Owner owner,
            Models.Identification identification,
            Guid? virtualBankAccountId = null,
            string name = null,
            string remittanceInformation = null)
        {
            this.VirtualBankAccountId = virtualBankAccountId;
            this.Name = name;
            this.Currency = currency;
            this.Owner = owner;
            this.Identification = identification;
            this.RemittanceInformation = remittanceInformation;
        }

        /// <summary>
        /// Virtual bank account request unique identifier.
        /// </summary>
        [JsonProperty("virtual_bank_account_id", NullValueHandling = NullValueHandling.Ignore)]
        public Guid? VirtualBankAccountId { get; set; }

        /// <summary>
        /// Name of the recipient account for the SEPA Credit Transfer
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        /// <summary>
        /// Alphabetic three-letter [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) currency code.
        /// * EUR — Euro.
        /// * GBP — Pound Sterling.
        /// </summary>
        [JsonProperty("currency")]
        public Models.Currency Currency { get; set; }

        /// <summary>
        /// Owner of the virtual bank account
        /// </summary>
        [JsonProperty("owner")]
        public Models.Owner Owner { get; set; }

        /// <summary>
        /// Identification details
        /// </summary>
        [JsonProperty("identification")]
        public Models.Identification Identification { get; set; }

        /// <summary>
        /// Payment reference the one that should be used for SEPA Credit Transfer
        /// </summary>
        [JsonProperty("remittance_information", NullValueHandling = NullValueHandling.Ignore)]
        public string RemittanceInformation { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Datum4 : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"VirtualBankAccountId = {(this.VirtualBankAccountId == null ? "null" : this.VirtualBankAccountId.ToString())}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"Currency = {this.Currency}");
            toStringOutput.Add($"Owner = {(this.Owner == null ? "null" : this.Owner.ToString())}");
            toStringOutput.Add($"Identification = {(this.Identification == null ? "null" : this.Identification.ToString())}");
            toStringOutput.Add($"RemittanceInformation = {this.RemittanceInformation ?? "null"}");
        }
    }
}