// <copyright file="Details2.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// Details2.
    /// </summary>
    public class Details2
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Details2"/> class.
        /// </summary>
        public Details2()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Details2"/> class.
        /// </summary>
        /// <param name="currentYearSubscription">current_year_subscription.</param>
        public Details2(
            Models.CurrentYearSubscription currentYearSubscription)
        {
            this.CurrentYearSubscription = currentYearSubscription;
        }

        /// <summary>
        /// Details related to the current year’s subscription being transferred.
        /// Required if transfer_type is ISA_INTERNAL.
        /// </summary>
        [JsonProperty("current_year_subscription")]
        public Models.CurrentYearSubscription CurrentYearSubscription { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Details2 : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"CurrentYearSubscription = {(this.CurrentYearSubscription == null ? "null" : this.CurrentYearSubscription.ToString())}");
        }
    }
}