// <copyright file="DocumentType5.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// DocumentType5.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum DocumentType5
    {
        /// <summary>
        /// BirthCertificate.
        /// </summary>
        [EnumMember(Value = "BIRTH_CERTIFICATE")]
        BirthCertificate,

        /// <summary>
        /// SoleCustodyProof.
        /// </summary>
        [EnumMember(Value = "SOLE_CUSTODY_PROOF")]
        SoleCustodyProof
    }
}