// <copyright file="FeeConfiguration.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;
using UpvestInvestmentApi.Standard.Models.Containers;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// FeeConfiguration.
    /// </summary>
    public class FeeConfiguration
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FeeConfiguration"/> class.
        /// </summary>
        public FeeConfiguration()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FeeConfiguration"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="createdAt">created_at.</param>
        /// <param name="updatedAt">updated_at.</param>
        /// <param name="label">label.</param>
        /// <param name="currency">currency.</param>
        /// <param name="chargeMethod">charge_method.</param>
        /// <param name="valueType">value_type.</param>
        /// <param name="applicationType">application_type.</param>
        /// <param name="baseAmountScope">base_amount_scope.</param>
        /// <param name="tiers">tiers.</param>
        public FeeConfiguration(
            Guid id,
            DateTime createdAt,
            DateTime updatedAt,
            string label,
            Models.Currency currency,
            string chargeMethod,
            Models.ValueType valueType,
            string applicationType,
            string baseAmountScope,
            List<FeeConfigurationTiers> tiers)
        {
            this.Id = id;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.Label = label;
            this.Currency = currency;
            this.ChargeMethod = chargeMethod;
            this.ValueType = valueType;
            this.ApplicationType = applicationType;
            this.BaseAmountScope = baseAmountScope;
            this.Tiers = tiers;
        }

        /// <summary>
        /// Universally Unique Identifier (UUID) of the transaction fee model.
        /// </summary>
        [JsonProperty("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Date and time when the resource was created. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Date and time when the resource was last updated. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("updated_at")]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// A human-readable label for the transaction fee model.
        /// </summary>
        [JsonProperty("label")]
        public string Label { get; set; }

        /// <summary>
        /// Alphabetic three-letter [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) currency code.
        /// * EUR - Euro
        /// * GBP - Pound Sterling
        /// </summary>
        [JsonProperty("currency")]
        public Models.Currency Currency { get; set; }

        /// <summary>
        /// Indicates how the transaction fee is charged.
        /// * `CHARGED_BY_CLIENT` — The fee is charged by the client as part of post-trade settlement; the fee movement occurs outside Upvest cash balances.
        /// </summary>
        [JsonProperty("charge_method")]
        public string ChargeMethod { get; set; }

        /// <summary>
        /// The value type of the transaction fee model.
        /// * `ABSOLUTE` — Tier fees are fixed cash amounts.
        /// * `RELATIVE` — Tier fees are percentages of the order value, expressed in basis points.
        /// </summary>
        [JsonProperty("value_type")]
        public Models.ValueType ValueType { get; set; }

        /// <summary>
        /// The application type of the transaction fee model.
        /// * `VOLUME` — The full order value is assessed against the tier thresholds, and the matching tier's fee applies to the total order volume.
        /// </summary>
        [JsonProperty("application_type")]
        public string ApplicationType { get; set; }

        /// <summary>
        /// The scope of the base amount that fee tiers are evaluated against.
        /// * `ORDER` — Tiers are evaluated against the total cash value of each order.
        /// </summary>
        [JsonProperty("base_amount_scope")]
        public string BaseAmountScope { get; set; }

        /// <summary>
        /// The tiers of the transaction fee model.
        /// </summary>
        [JsonProperty("tiers")]
        public List<FeeConfigurationTiers> Tiers { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"FeeConfiguration : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {this.Id}");
            toStringOutput.Add($"CreatedAt = {this.CreatedAt}");
            toStringOutput.Add($"UpdatedAt = {this.UpdatedAt}");
            toStringOutput.Add($"Label = {this.Label ?? "null"}");
            toStringOutput.Add($"Currency = {this.Currency}");
            toStringOutput.Add($"ChargeMethod = {this.ChargeMethod ?? "null"}");
            toStringOutput.Add($"ValueType = {this.ValueType}");
            toStringOutput.Add($"ApplicationType = {this.ApplicationType ?? "null"}");
            toStringOutput.Add($"BaseAmountScope = {this.BaseAmountScope ?? "null"}");
            toStringOutput.Add($"Tiers = {(this.Tiers == null ? "null" : this.Tiers.ToString())}");
        }
    }
}