// <copyright file="FilesMetadata.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// FilesMetadata.
    /// </summary>
    public class FilesMetadata
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FilesMetadata"/> class.
        /// </summary>
        public FilesMetadata()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FilesMetadata"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="createdAt">created_at.</param>
        /// <param name="updatedAt">updated_at.</param>
        /// <param name="signedUrl">signed_url.</param>
        /// <param name="fileName">file_name.</param>
        /// <param name="contentLength">content_length.</param>
        /// <param name="checksum">checksum.</param>
        public FilesMetadata(
            Guid id,
            DateTime createdAt,
            DateTime updatedAt,
            string signedUrl,
            string fileName,
            int contentLength,
            string checksum)
        {
            this.Id = id;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.SignedUrl = signedUrl;
            this.FileName = fileName;
            this.ContentLength = contentLength;
            this.Checksum = checksum;
        }

        /// <summary>
        /// Files metadata identifier.
        /// </summary>
        [JsonProperty("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Date and time when the resource was created. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Date and time when the resource was last updated. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("updated_at")]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Files download URL.
        /// </summary>
        [JsonProperty("signed_url")]
        public string SignedUrl { get; set; }

        /// <summary>
        /// Name of the file.
        /// </summary>
        [JsonProperty("file_name")]
        public string FileName { get; set; }

        /// <summary>
        /// Length of the file
        /// </summary>
        [JsonProperty("content_length")]
        public int ContentLength { get; set; }

        /// <summary>
        /// CRC32 of the files content
        /// </summary>
        [JsonProperty("checksum")]
        public string Checksum { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"FilesMetadata : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {this.Id}");
            toStringOutput.Add($"CreatedAt = {this.CreatedAt}");
            toStringOutput.Add($"UpdatedAt = {this.UpdatedAt}");
            toStringOutput.Add($"SignedUrl = {this.SignedUrl ?? "null"}");
            toStringOutput.Add($"FileName = {this.FileName ?? "null"}");
            toStringOutput.Add($"ContentLength = {this.ContentLength}");
            toStringOutput.Add($"Checksum = {this.Checksum ?? "null"}");
        }
    }
}