// <copyright file="Identification8.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using UpvestInvestmentApi.Standard.Utilities;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// Identification8.
    /// </summary>
    public class Identification8
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Identification8"/> class.
        /// </summary>
        public Identification8()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Identification8"/> class.
        /// </summary>
        /// <param name="companyName">company_name.</param>
        /// <param name="incorporationDate">incorporation_date.</param>
        /// <param name="legalDesignation">legal_designation.</param>
        /// <param name="commonReportingStandards">common_reporting_standards.</param>
        /// <param name="districtCourt">district_court.</param>
        /// <param name="legalEntityIdentifier">legal_entity_identifier.</param>
        public Identification8(
            string companyName,
            string incorporationDate,
            Models.LegalDesignation legalDesignation,
            Models.CommonReportingStandards commonReportingStandards,
            string districtCourt = null,
            string legalEntityIdentifier = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.CompanyName = companyName;
            this.IncorporationDate = incorporationDate;
            this.DistrictCourt = districtCourt;
            this.LegalDesignation = legalDesignation;
            this.LegalEntityIdentifier = legalEntityIdentifier;
            this.CommonReportingStandards = commonReportingStandards;
        }

        /// <summary>
        /// Name of the company.
        /// </summary>
        [JsonProperty("company_name")]
        public string CompanyName { get; set; }

        /// <summary>
        /// Incorporation date of the business in YYYY-MM-DD format. [RFC 3339, section 5.6](https://json-schema.org/draft/2020-12/json-schema-validation.html#RFC3339)
        /// </summary>
        [JsonProperty("incorporation_date")]
        public string IncorporationDate { get; set; }

        /// <summary>
        /// District court where the company is registered.
        /// </summary>
        [JsonProperty("district_court", NullValueHandling = NullValueHandling.Ignore)]
        public string DistrictCourt { get; set; }

        /// <summary>
        /// Country specific legal designation of the company.
        /// </summary>
        [JsonProperty("legal_designation")]
        public Models.LegalDesignation LegalDesignation { get; set; }

        /// <summary>
        /// Legal Entity Identifier (LEI) of the company. A 20-character alphanumeric code as defined by [ISO 17442](https://en.wikipedia.org/wiki/Legal_Entity_Identifier).
        /// </summary>
        [JsonProperty("legal_entity_identifier", NullValueHandling = NullValueHandling.Ignore)]
        public string LegalEntityIdentifier { get; set; }

        /// <summary>
        /// Common reporting standards information.
        /// </summary>
        [JsonProperty("common_reporting_standards")]
        public Models.CommonReportingStandards CommonReportingStandards { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Identification8 : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"CompanyName = {this.CompanyName ?? "null"}");
            toStringOutput.Add($"IncorporationDate = {this.IncorporationDate ?? "null"}");
            toStringOutput.Add($"DistrictCourt = {this.DistrictCourt ?? "null"}");
            toStringOutput.Add($"LegalDesignation = {this.LegalDesignation}");
            toStringOutput.Add($"LegalEntityIdentifier = {this.LegalEntityIdentifier ?? "null"}");
            toStringOutput.Add($"CommonReportingStandards = {(this.CommonReportingStandards == null ? "null" : this.CommonReportingStandards.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}