// <copyright file="InstrumentsVenuesPricesLatestResponse.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// InstrumentsVenuesPricesLatestResponse.
    /// </summary>
    public class InstrumentsVenuesPricesLatestResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstrumentsVenuesPricesLatestResponse"/> class.
        /// </summary>
        public InstrumentsVenuesPricesLatestResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InstrumentsVenuesPricesLatestResponse"/> class.
        /// </summary>
        /// <param name="priceQuality">price_quality.</param>
        /// <param name="currency">currency.</param>
        /// <param name="bids">bids.</param>
        /// <param name="asks">asks.</param>
        /// <param name="lastTrade">last_trade.</param>
        public InstrumentsVenuesPricesLatestResponse(
            Models.PriceQuality2 priceQuality,
            Models.Currency currency,
            List<Models.Bid> bids = null,
            List<Models.Ask> asks = null,
            Models.LastTrade lastTrade = null)
        {
            this.PriceQuality = priceQuality;
            this.Currency = currency;
            this.Bids = bids;
            this.Asks = asks;
            this.LastTrade = lastTrade;
        }

        /// <summary>
        /// The quality of the price data returned.
        /// * REALTIME — Priced in real time.
        /// * DELAYED — Priced with a delay set by the data owner.
        /// </summary>
        [JsonProperty("price_quality")]
        public Models.PriceQuality2 PriceQuality { get; set; }

        /// <summary>
        /// Alphabetic three-letter [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) currency code.
        /// * EUR — Euro.
        /// * GBP — Pound Sterling.
        /// </summary>
        [JsonProperty("currency")]
        public Models.Currency Currency { get; set; }

        /// <summary>
        /// Bids for the instrument.
        /// </summary>
        [JsonProperty("bids", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.Bid> Bids { get; set; }

        /// <summary>
        /// Asks for the instrument.
        /// </summary>
        [JsonProperty("asks", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.Ask> Asks { get; set; }

        /// <summary>
        /// A single trade in an instrument, with the price and size at which it executed.
        /// </summary>
        [JsonProperty("last_trade", NullValueHandling = NullValueHandling.Ignore)]
        public Models.LastTrade LastTrade { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"InstrumentsVenuesPricesLatestResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"PriceQuality = {this.PriceQuality}");
            toStringOutput.Add($"Currency = {this.Currency}");
            toStringOutput.Add($"Bids = {(this.Bids == null ? "null" : $"[{string.Join(", ", this.Bids)} ]")}");
            toStringOutput.Add($"Asks = {(this.Asks == null ? "null" : $"[{string.Join(", ", this.Asks)} ]")}");
            toStringOutput.Add($"LastTrade = {(this.LastTrade == null ? "null" : this.LastTrade.ToString())}");
        }
    }
}