// <copyright file="OrderExAnteServiceCost.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// OrderExAnteServiceCost.
    /// </summary>
    public class OrderExAnteServiceCost
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderExAnteServiceCost"/> class.
        /// </summary>
        public OrderExAnteServiceCost()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OrderExAnteServiceCost"/> class.
        /// </summary>
        /// <param name="oneOff">one_off.</param>
        /// <param name="ongoing">ongoing.</param>
        /// <param name="transaction">transaction.</param>
        /// <param name="ancillary">ancillary.</param>
        /// <param name="incidental">incidental.</param>
        /// <param name="total">total.</param>
        public OrderExAnteServiceCost(
            Models.Cost oneOff = null,
            Models.Cost ongoing = null,
            Models.Cost transaction = null,
            Models.Cost ancillary = null,
            Models.Cost incidental = null,
            Models.Cost total = null)
        {
            this.OneOff = oneOff;
            this.Ongoing = ongoing;
            this.Transaction = transaction;
            this.Ancillary = ancillary;
            this.Incidental = incidental;
            this.Total = total;
        }

        /// <summary>
        /// Gets or sets OneOff.
        /// </summary>
        [JsonProperty("one_off", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Cost OneOff { get; set; }

        /// <summary>
        /// Gets or sets Ongoing.
        /// </summary>
        [JsonProperty("ongoing", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Cost Ongoing { get; set; }

        /// <summary>
        /// Gets or sets Transaction.
        /// </summary>
        [JsonProperty("transaction", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Cost Transaction { get; set; }

        /// <summary>
        /// Gets or sets Ancillary.
        /// </summary>
        [JsonProperty("ancillary", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Cost Ancillary { get; set; }

        /// <summary>
        /// Gets or sets Incidental.
        /// </summary>
        [JsonProperty("incidental", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Cost Incidental { get; set; }

        /// <summary>
        /// Gets or sets Total.
        /// </summary>
        [JsonProperty("total", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Cost Total { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"OrderExAnteServiceCost : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"OneOff = {(this.OneOff == null ? "null" : this.OneOff.ToString())}");
            toStringOutput.Add($"Ongoing = {(this.Ongoing == null ? "null" : this.Ongoing.ToString())}");
            toStringOutput.Add($"Transaction = {(this.Transaction == null ? "null" : this.Transaction.ToString())}");
            toStringOutput.Add($"Ancillary = {(this.Ancillary == null ? "null" : this.Ancillary.ToString())}");
            toStringOutput.Add($"Incidental = {(this.Incidental == null ? "null" : this.Incidental.ToString())}");
            toStringOutput.Add($"Total = {(this.Total == null ? "null" : this.Total.ToString())}");
        }
    }
}