// <copyright file="OrderCancelResponse.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// OrderCancelResponse.
    /// </summary>
    public class OrderCancelResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderCancelResponse"/> class.
        /// </summary>
        public OrderCancelResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OrderCancelResponse"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        public OrderCancelResponse(
            Guid id)
        {
            this.Id = id;
        }

        /// <summary>
        /// Unique identifier for an order. Universally Unique Identifier (UUID).
        /// </summary>
        [JsonProperty("id")]
        public Guid Id { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"OrderCancelResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {this.Id}");
        }
    }
}