// <copyright file="OrderExAnteAggregatedCost.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// OrderExAnteAggregatedCost.
    /// </summary>
    public class OrderExAnteAggregatedCost
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderExAnteAggregatedCost"/> class.
        /// </summary>
        public OrderExAnteAggregatedCost()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OrderExAnteAggregatedCost"/> class.
        /// </summary>
        /// <param name="product">product.</param>
        /// <param name="service">service.</param>
        /// <param name="thirdParty">third_party.</param>
        /// <param name="total">total.</param>
        public OrderExAnteAggregatedCost(
            Models.Cost product = null,
            Models.Cost service = null,
            Models.Cost thirdParty = null,
            Models.Cost total = null)
        {
            this.Product = product;
            this.Service = service;
            this.ThirdParty = thirdParty;
            this.Total = total;
        }

        /// <summary>
        /// Gets or sets Product.
        /// </summary>
        [JsonProperty("product", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Cost Product { get; set; }

        /// <summary>
        /// Gets or sets Service.
        /// </summary>
        [JsonProperty("service", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Cost Service { get; set; }

        /// <summary>
        /// Gets or sets ThirdParty.
        /// </summary>
        [JsonProperty("third_party", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Cost ThirdParty { get; set; }

        /// <summary>
        /// Gets or sets Total.
        /// </summary>
        [JsonProperty("total", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Cost Total { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"OrderExAnteAggregatedCost : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Product = {(this.Product == null ? "null" : this.Product.ToString())}");
            toStringOutput.Add($"Service = {(this.Service == null ? "null" : this.Service.ToString())}");
            toStringOutput.Add($"ThirdParty = {(this.ThirdParty == null ? "null" : this.ThirdParty.ToString())}");
            toStringOutput.Add($"Total = {(this.Total == null ? "null" : this.Total.ToString())}");
        }
    }
}