// <copyright file="PaymentsWithdrawal.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// PaymentsWithdrawal.
    /// </summary>
    public class PaymentsWithdrawal
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentsWithdrawal"/> class.
        /// </summary>
        public PaymentsWithdrawal()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentsWithdrawal"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="createdAt">created_at.</param>
        /// <param name="updatedAt">updated_at.</param>
        /// <param name="referenceAccountId">reference_account_id.</param>
        /// <param name="accountGroupId">account_group_id.</param>
        /// <param name="amount">amount.</param>
        /// <param name="currency">currency.</param>
        /// <param name="remittanceInformation">remittance_information.</param>
        /// <param name="userId">user_id.</param>
        /// <param name="taxes">taxes.</param>
        /// <param name="status">status.</param>
        /// <param name="cancellationReason">cancellation_reason.</param>
        /// <param name="purposeCode">purpose_code.</param>
        public PaymentsWithdrawal(
            Guid id,
            DateTime createdAt,
            DateTime updatedAt,
            Guid referenceAccountId,
            Guid accountGroupId,
            string amount,
            Models.Currency currency,
            string remittanceInformation,
            Guid? userId = null,
            List<Models.Tax> taxes = null,
            Models.Status34? status = null,
            Models.CancellationReasonCodeForWithdrawal? cancellationReason = null,
            string purposeCode = null)
        {
            this.Id = id;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.ReferenceAccountId = referenceAccountId;
            this.AccountGroupId = accountGroupId;
            this.UserId = userId;
            this.Amount = amount;
            this.Currency = currency;
            this.RemittanceInformation = remittanceInformation;
            this.Taxes = taxes;
            this.Status = status;
            this.CancellationReason = cancellationReason;
            this.PurposeCode = purposeCode;
        }

        /// <summary>
        /// Cash withdrawal unique identifier
        /// </summary>
        [JsonProperty("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Date and time when the resource was created. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Date and time when the resource was last updated. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("updated_at")]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Reference account unique identifier.
        /// </summary>
        [JsonProperty("reference_account_id")]
        public Guid ReferenceAccountId { get; set; }

        /// <summary>
        /// Universally Unique Identifier (UUID) of the account group.
        /// </summary>
        [JsonProperty("account_group_id")]
        public Guid AccountGroupId { get; set; }

        /// <summary>
        /// The ID of the user. For business-initiated withdrawals, this field will be absent.
        /// </summary>
        [JsonProperty("user_id", NullValueHandling = NullValueHandling.Ignore)]
        public Guid? UserId { get; set; }

        /// <summary>
        /// A positive cash amount, as a decimal string with up to two decimal places.
        /// </summary>
        [JsonProperty("amount")]
        public string Amount { get; set; }

        /// <summary>
        /// Alphabetic three-letter [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) currency code.
        /// * EUR — Euro.
        /// * GBP — Pound Sterling.
        /// </summary>
        [JsonProperty("currency")]
        public Models.Currency Currency { get; set; }

        /// <summary>
        /// Payment reference the end user will see in their bank statement for the corresponding credit transfer booking (“Verwendungszweck”). We recommend that you keep this info concise and avoid special characters or non-standardised formatting. See the ([Cash balance withdrawal guide](/documentation/guides/payments/cash_balances/cash_withdrawal)).
        /// </summary>
        [JsonProperty("remittance_information")]
        public string RemittanceInformation { get; set; }

        /// <summary>
        /// Gets or sets Taxes.
        /// </summary>
        [JsonProperty("taxes", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.Tax> Taxes { get; set; }

        /// <summary>
        /// Status of the withdrawal
        /// * NEW - Withdrawal is created but not started processing.
        /// * PROCESSING - Withdrawal is in processing.
        /// * CONFIRMED - Withdrawal was successfully sent to the bank for processing.
        /// * CANCELLED - Withdrawal was cancelled. **Note**: In rare instances, a bank may reject a withdrawal after it has been confirmed.
        /// For more information, see the [Potential cancellation after confirmation](/documentation/guides/payments/cash_balances/cash_withdrawal#potential-cancellation-after-confirmation) section of the guide.
        /// </summary>
        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Status34? Status { get; set; }

        /// <summary>
        /// Reason the withdrawal was cancelled. The field is present in case the withdrawal has a status of CANCELLED.
        /// * CANCELLED_BY_BANK - The payment was not completed by your bank. Please check your account details or contact support.
        /// * CANCELLED_BY_UPVEST - The payment was cancelled. Contact support for details.
        /// * CANCELLED_BY_CLIENT - The payment was cancelled at your request.
        /// * OTHER - Reason not available (applies to historical data only).
        /// </summary>
        [JsonProperty("cancellation_reason", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CancellationReasonCodeForWithdrawal? CancellationReason { get; set; }

        /// <summary>
        /// Purpose of the payment based on *ExternalPurpose1Code* from [ISO 20022](https://www.iso20022.org/catalogue-messages/additional-content-messages/external-code-sets).
        /// </summary>
        [JsonProperty("purpose_code", NullValueHandling = NullValueHandling.Ignore)]
        public string PurposeCode { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PaymentsWithdrawal : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {this.Id}");
            toStringOutput.Add($"CreatedAt = {this.CreatedAt}");
            toStringOutput.Add($"UpdatedAt = {this.UpdatedAt}");
            toStringOutput.Add($"ReferenceAccountId = {this.ReferenceAccountId}");
            toStringOutput.Add($"AccountGroupId = {this.AccountGroupId}");
            toStringOutput.Add($"UserId = {(this.UserId == null ? "null" : this.UserId.ToString())}");
            toStringOutput.Add($"Amount = {this.Amount ?? "null"}");
            toStringOutput.Add($"Currency = {this.Currency}");
            toStringOutput.Add($"RemittanceInformation = {this.RemittanceInformation ?? "null"}");
            toStringOutput.Add($"Taxes = {(this.Taxes == null ? "null" : $"[{string.Join(", ", this.Taxes)} ]")}");
            toStringOutput.Add($"Status = {(this.Status == null ? "null" : this.Status.ToString())}");
            toStringOutput.Add($"CancellationReason = {(this.CancellationReason == null ? "null" : this.CancellationReason.ToString())}");
            toStringOutput.Add($"PurposeCode = {this.PurposeCode ?? "null"}");
        }
    }
}