// <copyright file="PortfoliosConfigurationUpdateRequest.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// PortfoliosConfigurationUpdateRequest.
    /// </summary>
    public class PortfoliosConfigurationUpdateRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PortfoliosConfigurationUpdateRequest"/> class.
        /// </summary>
        public PortfoliosConfigurationUpdateRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PortfoliosConfigurationUpdateRequest"/> class.
        /// </summary>
        /// <param name="allocationId">allocation_id.</param>
        /// <param name="rebalancingStrategyIds">rebalancing_strategy_ids.</param>
        public PortfoliosConfigurationUpdateRequest(
            Guid? allocationId = null,
            List<Guid> rebalancingStrategyIds = null)
        {
            this.AllocationId = allocationId;
            this.RebalancingStrategyIds = rebalancingStrategyIds;
        }

        /// <summary>
        /// Universally Unique Identifier (UUID) of a portfolio allocation.
        /// </summary>
        [JsonProperty("allocation_id", NullValueHandling = NullValueHandling.Ignore)]
        public Guid? AllocationId { get; set; }

        /// <summary>
        /// List of rebalancing strategy ids
        /// </summary>
        [JsonProperty("rebalancing_strategy_ids", NullValueHandling = NullValueHandling.Ignore)]
        public List<Guid> RebalancingStrategyIds { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PortfoliosConfigurationUpdateRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AllocationId = {(this.AllocationId == null ? "null" : this.AllocationId.ToString())}");
            toStringOutput.Add($"RebalancingStrategyIds = {(this.RebalancingStrategyIds == null ? "null" : $"[{string.Join(", ", this.RebalancingStrategyIds)} ]")}");
        }
    }
}