// <copyright file="PortfoliosRebalancingExecution.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// PortfoliosRebalancingExecution.
    /// </summary>
    public class PortfoliosRebalancingExecution
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PortfoliosRebalancingExecution"/> class.
        /// </summary>
        public PortfoliosRebalancingExecution()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PortfoliosRebalancingExecution"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="createdAt">created_at.</param>
        /// <param name="updatedAt">updated_at.</param>
        /// <param name="accounts">accounts.</param>
        /// <param name="allocations">allocations.</param>
        public PortfoliosRebalancingExecution(
            Guid id,
            DateTime createdAt,
            DateTime updatedAt,
            List<Guid> accounts = null,
            List<Guid> allocations = null)
        {
            this.Id = id;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.Accounts = accounts;
            this.Allocations = allocations;
        }

        /// <summary>
        /// Universally Unique Identifier (UUID) of a portfolio order.
        /// </summary>
        [JsonProperty("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Date and time when the resource was created. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Date and time when the resource was last updated. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("updated_at")]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Accounts associated with this rebalancing execution
        /// </summary>
        [JsonProperty("accounts", NullValueHandling = NullValueHandling.Ignore)]
        public List<Guid> Accounts { get; set; }

        /// <summary>
        /// Allocations associated with this rebalancing execution
        /// </summary>
        [JsonProperty("allocations", NullValueHandling = NullValueHandling.Ignore)]
        public List<Guid> Allocations { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PortfoliosRebalancingExecution : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {this.Id}");
            toStringOutput.Add($"CreatedAt = {this.CreatedAt}");
            toStringOutput.Add($"UpdatedAt = {this.UpdatedAt}");
            toStringOutput.Add($"Accounts = {(this.Accounts == null ? "null" : $"[{string.Join(", ", this.Accounts)} ]")}");
            toStringOutput.Add($"Allocations = {(this.Allocations == null ? "null" : $"[{string.Join(", ", this.Allocations)} ]")}");
        }
    }
}