// <copyright file="PortfoliosOrdersListResponse.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// PortfoliosOrdersListResponse.
    /// </summary>
    public class PortfoliosOrdersListResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PortfoliosOrdersListResponse"/> class.
        /// </summary>
        public PortfoliosOrdersListResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PortfoliosOrdersListResponse"/> class.
        /// </summary>
        /// <param name="meta">meta.</param>
        /// <param name="data">data.</param>
        public PortfoliosOrdersListResponse(
            Models.Meta meta,
            List<Models.PortfoliosOrder> data)
        {
            this.Meta = meta;
            this.Data = data;
        }

        /// <summary>
        /// Gets or sets Meta.
        /// </summary>
        [JsonProperty("meta")]
        public Models.Meta Meta { get; set; }

        /// <summary>
        /// Gets or sets Data.
        /// </summary>
        [JsonProperty("data")]
        public List<Models.PortfoliosOrder> Data { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PortfoliosOrdersListResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Meta = {(this.Meta == null ? "null" : this.Meta.ToString())}");
            toStringOutput.Add($"Data = {(this.Data == null ? "null" : $"[{string.Join(", ", this.Data)} ]")}");
        }
    }
}