// <copyright file="PortfoliosRebalancingExecutionOrder.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// PortfoliosRebalancingExecutionOrder.
    /// </summary>
    public class PortfoliosRebalancingExecutionOrder
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PortfoliosRebalancingExecutionOrder"/> class.
        /// </summary>
        public PortfoliosRebalancingExecutionOrder()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PortfoliosRebalancingExecutionOrder"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="executionId">execution_id.</param>
        /// <param name="accountId">account_id.</param>
        /// <param name="status">status.</param>
        /// <param name="createdAt">created_at.</param>
        /// <param name="updatedAt">updated_at.</param>
        /// <param name="portfolioOrderId">portfolio_order_id.</param>
        /// <param name="cancellationReason">cancellation_reason.</param>
        /// <param name="cancellationDetails">cancellation_details.</param>
        public PortfoliosRebalancingExecutionOrder(
            Guid id,
            Guid executionId,
            Guid accountId,
            Models.Status71 status,
            DateTime createdAt,
            DateTime updatedAt,
            Guid? portfolioOrderId = null,
            Models.CancellationReason3? cancellationReason = null,
            string cancellationDetails = null)
        {
            this.Id = id;
            this.ExecutionId = executionId;
            this.AccountId = accountId;
            this.PortfolioOrderId = portfolioOrderId;
            this.Status = status;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.CancellationReason = cancellationReason;
            this.CancellationDetails = cancellationDetails;
        }

        /// <summary>
        /// Universally Unique Identifier (UUID) of a rebalancing execution order.
        /// </summary>
        [JsonProperty("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Universally Unique Identifier (UUID) of a portfolio rebalancing execution.
        /// </summary>
        [JsonProperty("execution_id")]
        public Guid ExecutionId { get; set; }

        /// <summary>
        /// Account unique identifier.
        /// </summary>
        [JsonProperty("account_id")]
        public Guid AccountId { get; set; }

        /// <summary>
        /// Gets or sets PortfolioOrderId.
        /// </summary>
        [JsonProperty("portfolio_order_id", NullValueHandling = NullValueHandling.Include)]
        public Guid? PortfolioOrderId { get; set; }

        /// <summary>
        /// Status of the Rebalancing Execution Order.
        /// * NEW -
        /// * PROCESSING -
        /// * FILLED -
        /// * CANCELLED -
        /// </summary>
        [JsonProperty("status")]
        public Models.Status71 Status { get; set; }

        /// <summary>
        /// Date and time when the resource was created. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Date and time when the resource was last updated. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("updated_at")]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Reason for Rebalancing Execution Order Cancellation. The field is present in case the Order has a status of CANCELLED.
        /// * ACCOUNT_IS_EMPTY -
        /// * ACCOUNT_NOT_FOUND -
        /// * CANCELLED_BY_CLIENT -
        /// * CANCELLED_BY_UPVEST -
        /// * CONFIGURATION_IS_MISSING -
        /// * INVALID_ACCOUNT_TYPE -
        /// * PORTFOLIO_IS_BALANCED -
        /// * UNKNOWN -
        /// </summary>
        [JsonProperty("cancellation_reason", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CancellationReason3? CancellationReason { get; set; }

        /// <summary>
        /// Gets or sets CancellationDetails.
        /// </summary>
        [JsonProperty("cancellation_details", NullValueHandling = NullValueHandling.Ignore)]
        public string CancellationDetails { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PortfoliosRebalancingExecutionOrder : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {this.Id}");
            toStringOutput.Add($"ExecutionId = {this.ExecutionId}");
            toStringOutput.Add($"AccountId = {this.AccountId}");
            toStringOutput.Add($"PortfolioOrderId = {(this.PortfolioOrderId == null ? "null" : this.PortfolioOrderId.ToString())}");
            toStringOutput.Add($"Status = {this.Status}");
            toStringOutput.Add($"CreatedAt = {this.CreatedAt}");
            toStringOutput.Add($"UpdatedAt = {this.UpdatedAt}");
            toStringOutput.Add($"CancellationReason = {(this.CancellationReason == null ? "null" : this.CancellationReason.ToString())}");
            toStringOutput.Add($"CancellationDetails = {this.CancellationDetails ?? "null"}");
        }
    }
}