// <copyright file="PriceQuality2.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// PriceQuality2.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum PriceQuality2
    {
        /// <summary>
        /// Realtime.
        /// </summary>
        [EnumMember(Value = "REALTIME")]
        Realtime,

        /// <summary>
        /// Delayed.
        /// </summary>
        [EnumMember(Value = "DELAYED")]
        Delayed
    }
}