// <copyright file="PriceQuality3.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// PriceQuality3.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum PriceQuality3
    {
        /// <summary>
        /// Eod.
        /// </summary>
        [EnumMember(Value = "EOD")]
        Eod,

        /// <summary>
        /// HighestAvailable.
        /// </summary>
        [EnumMember(Value = "HIGHEST_AVAILABLE")]
        HighestAvailable
    }
}