// <copyright file="QuoteCurrency.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// QuoteCurrency.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum QuoteCurrency
    {
        /// <summary>
        /// Eur.
        /// </summary>
        [EnumMember(Value = "EUR")]
        Eur,

        /// <summary>
        /// Gbp.
        /// </summary>
        [EnumMember(Value = "GBP")]
        Gbp,

        /// <summary>
        /// Usd.
        /// </summary>
        [EnumMember(Value = "USD")]
        Usd
    }
}