// <copyright file="RelativeTransactionFeeTier.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using UpvestInvestmentApi.Standard.Utilities;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// RelativeTransactionFeeTier.
    /// </summary>
    public class RelativeTransactionFeeTier
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RelativeTransactionFeeTier"/> class.
        /// </summary>
        public RelativeTransactionFeeTier()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RelativeTransactionFeeTier"/> class.
        /// </summary>
        /// <param name="tierId">tier_id.</param>
        /// <param name="baseAmountFrom">base_amount_from.</param>
        /// <param name="feeBps">fee_bps.</param>
        /// <param name="minFeeAmount">min_fee_amount.</param>
        /// <param name="maxFeeAmount">max_fee_amount.</param>
        public RelativeTransactionFeeTier(
            string tierId,
            string baseAmountFrom,
            string feeBps,
            string minFeeAmount = null,
            string maxFeeAmount = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.TierId = tierId;
            this.BaseAmountFrom = baseAmountFrom;
            this.FeeBps = feeBps;
            this.MinFeeAmount = minFeeAmount;
            this.MaxFeeAmount = maxFeeAmount;
        }

        /// <summary>
        /// Unique identifier of the fee tier within the transaction fee model. A numeric string of up to 63 digits.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("tier_id")]
        [JsonRequired]
        public string TierId { get; set; }

        /// <summary>
        /// A positive decimal amount, as a string.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("base_amount_from")]
        [JsonRequired]
        public string BaseAmountFrom { get; set; }

        /// <summary>
        /// A positive decimal amount, as a string.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("fee_bps")]
        [JsonRequired]
        public string FeeBps { get; set; }

        /// <summary>
        /// A positive decimal amount, as a string.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("min_fee_amount", NullValueHandling = NullValueHandling.Ignore)]
        public string MinFeeAmount { get; set; }

        /// <summary>
        /// A positive decimal amount, as a string.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("max_fee_amount", NullValueHandling = NullValueHandling.Ignore)]
        public string MaxFeeAmount { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"RelativeTransactionFeeTier : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"TierId = {this.TierId ?? "null"}");
            toStringOutput.Add($"BaseAmountFrom = {this.BaseAmountFrom ?? "null"}");
            toStringOutput.Add($"FeeBps = {this.FeeBps ?? "null"}");
            toStringOutput.Add($"MinFeeAmount = {this.MinFeeAmount ?? "null"}");
            toStringOutput.Add($"MaxFeeAmount = {this.MaxFeeAmount ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}