// <copyright file="ReportOrderExAnteCostCreateRequestSavingsPlan.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using UpvestInvestmentApi.Standard.Models.Containers;
using UpvestInvestmentApi.Standard.Utilities;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// ReportOrderExAnteCostCreateRequestSavingsPlan.
    /// </summary>
    public class ReportOrderExAnteCostCreateRequestSavingsPlan
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReportOrderExAnteCostCreateRequestSavingsPlan"/> class.
        /// </summary>
        public ReportOrderExAnteCostCreateRequestSavingsPlan()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReportOrderExAnteCostCreateRequestSavingsPlan"/> class.
        /// </summary>
        /// <param name="type">type.</param>
        /// <param name="order">order.</param>
        /// <param name="fees">fees.</param>
        /// <param name="inducements">inducements.</param>
        public ReportOrderExAnteCostCreateRequestSavingsPlan(
            string type,
            Models.ExAnteCostSavingsPlanOrder order,
            List<ReportOrderExAnteCostCreateRequestSavingsPlanFees> fees = null,
            List<Models.Inducement> inducements = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Type = type;
            this.Order = order;
            this.Fees = fees;
            this.Inducements = inducements;
        }

        /// <summary>
        /// The type of report must be “ORDER_EX_ANTE_COST_SAVINGS_PLAN”. Savings plan ex-ante reports are only supported for individual users, not for business entities.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("type")]
        [JsonRequired]
        public string Type { get; set; }

        /// <summary>
        /// Savings Plan Order details.
        /// </summary>
        [JsonProperty("order")]
        [JsonRequired]
        public Models.ExAnteCostSavingsPlanOrder Order { get; set; }

        /// <summary>
        /// Client fees.
        /// </summary>
        [JsonProperty("fees", NullValueHandling = NullValueHandling.Ignore)]
        public List<ReportOrderExAnteCostCreateRequestSavingsPlanFees> Fees { get; set; }

        /// <summary>
        /// Client inducements.
        /// </summary>
        [JsonProperty("inducements", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.Inducement> Inducements { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ReportOrderExAnteCostCreateRequestSavingsPlan : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Type = {this.Type ?? "null"}");
            toStringOutput.Add($"Order = {(this.Order == null ? "null" : this.Order.ToString())}");
            toStringOutput.Add($"Fees = {(this.Fees == null ? "null" : this.Fees.ToString())}");
            toStringOutput.Add($"Inducements = {(this.Inducements == null ? "null" : $"[{string.Join(", ", this.Inducements)} ]")}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}