// <copyright file="RoleType1.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// RoleType1.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum RoleType1
    {
        /// <summary>
        /// LegalRepresentative.
        /// </summary>
        [EnumMember(Value = "LEGAL_REPRESENTATIVE")]
        LegalRepresentative,

        /// <summary>
        /// AuthorisedSignatory.
        /// </summary>
        [EnumMember(Value = "AUTHORISED_SIGNATORY")]
        AuthorisedSignatory,

        /// <summary>
        /// UltimateBeneficialOwner.
        /// </summary>
        [EnumMember(Value = "ULTIMATE_BENEFICIAL_OWNER")]
        UltimateBeneficialOwner,

        /// <summary>
        /// ContractingExecutive.
        /// </summary>
        [EnumMember(Value = "CONTRACTING_EXECUTIVE")]
        ContractingExecutive,

        /// <summary>
        /// Trader.
        /// </summary>
        [EnumMember(Value = "TRADER")]
        Trader,

        /// <summary>
        /// SoleTrader.
        /// </summary>
        [EnumMember(Value = "SOLE_TRADER")]
        SoleTrader
    }
}