// <copyright file="RoleType2.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// RoleType2.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum RoleType2
    {
        /// <summary>
        /// Guardian.
        /// </summary>
        [EnumMember(Value = "GUARDIAN")]
        Guardian,

        /// <summary>
        /// Owner.
        /// </summary>
        [EnumMember(Value = "OWNER")]
        Owner
    }
}