// <copyright file="Salutation.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// Salutation.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Salutation
    {
        /// <summary>
        /// SalutationMale.
        /// </summary>
        [EnumMember(Value = "SALUTATION_MALE")]
        SalutationMale,

        /// <summary>
        /// SalutationFemale.
        /// </summary>
        [EnumMember(Value = "SALUTATION_FEMALE")]
        SalutationFemale,

        /// <summary>
        /// SalutationFemaleMarried.
        /// </summary>
        [EnumMember(Value = "SALUTATION_FEMALE_MARRIED")]
        SalutationFemaleMarried,

        /// <summary>
        /// SalutationDiverse.
        /// </summary>
        [EnumMember(Value = "SALUTATION_DIVERSE")]
        SalutationDiverse
    }
}