// <copyright file="SavingsPlanExecutionInstrument.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using UpvestInvestmentApi.Standard.Models.Containers;
using UpvestInvestmentApi.Standard.Utilities;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// SavingsPlanExecutionInstrument.
    /// </summary>
    public class SavingsPlanExecutionInstrument
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SavingsPlanExecutionInstrument"/> class.
        /// </summary>
        public SavingsPlanExecutionInstrument()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SavingsPlanExecutionInstrument"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="createdAt">created_at.</param>
        /// <param name="updatedAt">updated_at.</param>
        /// <param name="userId">user_id.</param>
        /// <param name="accountId">account_id.</param>
        /// <param name="savingsPlanId">savings_plan_id.</param>
        /// <param name="cashAmount">cash_amount.</param>
        /// <param name="currency">currency.</param>
        /// <param name="status">status.</param>
        /// <param name="type">type.</param>
        /// <param name="executionDate">execution_date.</param>
        /// <param name="orderId">order_id.</param>
        /// <param name="instrumentId">instrument_id.</param>
        /// <param name="instrumentIdType">instrument_id_type.</param>
        /// <param name="feeConfiguration">fee_configuration.</param>
        /// <param name="cancellationReason">cancellation_reason.</param>
        /// <param name="cancellationDetails">cancellation_details.</param>
        public SavingsPlanExecutionInstrument(
            Guid id,
            DateTime createdAt,
            DateTime updatedAt,
            Guid userId,
            Guid accountId,
            Guid savingsPlanId,
            string cashAmount,
            Models.Currency currency,
            Models.Status89 status,
            string type,
            string executionDate,
            SavingsPlanExecutionInstrumentOrderId orderId = null,
            SavingsPlanExecutionInstrumentInstrumentId instrumentId = null,
            Models.InstrumentIdType10? instrumentIdType = Models.InstrumentIdType10.Isin,
            List<Models.SavingsPlanFeeConfigurationOnlyForInstrument> feeConfiguration = null,
            Models.CancellationReasonCodeForSavingsPlanExecution? cancellationReason = null,
            string cancellationDetails = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Id = id;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.UserId = userId;
            this.AccountId = accountId;
            this.SavingsPlanId = savingsPlanId;
            this.OrderId = orderId;
            this.CashAmount = cashAmount;
            this.Currency = currency;
            this.Status = status;
            this.Type = type;
            this.ExecutionDate = executionDate;
            this.InstrumentId = instrumentId;
            this.InstrumentIdType = instrumentIdType;
            this.FeeConfiguration = feeConfiguration;
            this.CancellationReason = cancellationReason;
            this.CancellationDetails = cancellationDetails;
        }

        /// <summary>
        /// Universally Unique Identifier (UUID) of a savings plan execution.
        /// </summary>
        [JsonProperty("id")]
        [JsonRequired]
        public Guid Id { get; set; }

        /// <summary>
        /// Date and time when the resource was created. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("created_at")]
        [JsonRequired]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Date and time when the resource was last updated. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("updated_at")]
        [JsonRequired]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Unique identifier of the user, as a UUID.
        /// </summary>
        [JsonProperty("user_id")]
        [JsonRequired]
        public Guid UserId { get; set; }

        /// <summary>
        /// Universally Unique Identifier (UUID) of the account.
        /// </summary>
        [JsonProperty("account_id")]
        [JsonRequired]
        public Guid AccountId { get; set; }

        /// <summary>
        /// Universally Unique Identifier (UUID) of a savings plan.
        /// </summary>
        [JsonProperty("savings_plan_id")]
        [JsonRequired]
        public Guid SavingsPlanId { get; set; }

        /// <summary>
        /// Order unique identifier (Portfolio order or Instrument order)
        /// </summary>
        [JsonProperty("order_id", NullValueHandling = NullValueHandling.Include)]
        public SavingsPlanExecutionInstrumentOrderId OrderId { get; set; }

        /// <summary>
        /// A positive decimal amount, as a string.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("cash_amount")]
        [JsonRequired]
        public string CashAmount { get; set; }

        /// <summary>
        /// Alphabetic three-letter [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) currency code.
        /// * EUR — Euro.
        /// * GBP — Pound Sterling.
        /// </summary>
        [JsonProperty("currency")]
        [JsonRequired]
        public Models.Currency Currency { get; set; }

        /// <summary>
        /// Status of a Savings Plan Execution.
        /// * NEW -
        /// * PROCESSING -
        /// * FILLED -
        /// * SETTLED -
        /// * CANCELLED -
        /// </summary>
        [JsonProperty("status")]
        [JsonRequired]
        public Models.Status89 Status { get; set; }

        /// <summary>
        /// The type of savings plan must be "INSTRUMENT".
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("type")]
        [JsonRequired]
        public string Type { get; set; }

        /// <summary>
        /// Date of a savings plan execution in YYYY-MM-DD format.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("execution_date")]
        [JsonRequired]
        public string ExecutionDate { get; set; }

        /// <summary>
        /// Instrument unique identifier.
        /// </summary>
        [JsonProperty("instrument_id", NullValueHandling = NullValueHandling.Ignore)]
        public SavingsPlanExecutionInstrumentInstrumentId InstrumentId { get; set; }

        /// <summary>
        /// The type of the ID used in the request.
        /// * ISIN - International Securities Identification Number
        /// * WKN - German securities identification code
        /// </summary>
        [JsonProperty("instrument_id_type", NullValueHandling = NullValueHandling.Ignore)]
        public Models.InstrumentIdType10? InstrumentIdType { get; set; }

        /// <summary>
        /// Fee configuration for instrument-type savings plan executions. Specifies the transaction fee model to apply to each buy order placed on execution.
        /// </summary>
        [JsonProperty("fee_configuration", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.SavingsPlanFeeConfigurationOnlyForInstrument> FeeConfiguration { get; set; }

        /// <summary>
        /// Explains the reason why the savings plan execution was cancelled .
        /// * CANCELLED_BY_CLIENT: The savings plan execution was cancelled by the client.
        /// * CANCELLED_BY_UPVEST: The savings plan execution was cancelled by Upvest.
        /// </summary>
        [JsonProperty("cancellation_reason", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CancellationReasonCodeForSavingsPlanExecution? CancellationReason { get; set; }

        /// <summary>
        /// Human-readable description providing additional context about why the savings plan execution was cancelled.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("cancellation_details", NullValueHandling = NullValueHandling.Ignore)]
        public string CancellationDetails { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"SavingsPlanExecutionInstrument : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {this.Id}");
            toStringOutput.Add($"CreatedAt = {this.CreatedAt}");
            toStringOutput.Add($"UpdatedAt = {this.UpdatedAt}");
            toStringOutput.Add($"UserId = {this.UserId}");
            toStringOutput.Add($"AccountId = {this.AccountId}");
            toStringOutput.Add($"SavingsPlanId = {this.SavingsPlanId}");
            toStringOutput.Add($"OrderId = {(this.OrderId == null ? "null" : this.OrderId.ToString())}");
            toStringOutput.Add($"CashAmount = {this.CashAmount ?? "null"}");
            toStringOutput.Add($"Currency = {this.Currency}");
            toStringOutput.Add($"Status = {this.Status}");
            toStringOutput.Add($"Type = {this.Type ?? "null"}");
            toStringOutput.Add($"ExecutionDate = {this.ExecutionDate ?? "null"}");
            toStringOutput.Add($"InstrumentId = {(this.InstrumentId == null ? "null" : this.InstrumentId.ToString())}");
            toStringOutput.Add($"InstrumentIdType = {(this.InstrumentIdType == null ? "null" : this.InstrumentIdType.ToString())}");
            toStringOutput.Add($"FeeConfiguration = {(this.FeeConfiguration == null ? "null" : $"[{string.Join(", ", this.FeeConfiguration)} ]")}");
            toStringOutput.Add($"CancellationReason = {(this.CancellationReason == null ? "null" : this.CancellationReason.ToString())}");
            toStringOutput.Add($"CancellationDetails = {this.CancellationDetails ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}