// <copyright file="Side10.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// Side10.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Side10
    {
        /// <summary>
        /// Buy.
        /// </summary>
        [EnumMember(Value = "BUY")]
        Buy,

        /// <summary>
        /// Sell.
        /// </summary>
        [EnumMember(Value = "SELL")]
        Sell
    }
}