// <copyright file="Status73.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// Status73.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Status73
    {
        /// <summary>
        /// New.
        /// </summary>
        [EnumMember(Value = "NEW")]
        New,

        /// <summary>
        /// Processing.
        /// </summary>
        [EnumMember(Value = "PROCESSING")]
        Processing,

        /// <summary>
        /// Filled.
        /// </summary>
        [EnumMember(Value = "FILLED")]
        Filled,

        /// <summary>
        /// Cancelled.
        /// </summary>
        [EnumMember(Value = "CANCELLED")]
        Cancelled
    }
}