// <copyright file="Status29.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// Status29.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Status29
    {
        /// <summary>
        /// Confirmed.
        /// </summary>
        [EnumMember(Value = "CONFIRMED")]
        Confirmed,

        /// <summary>
        /// Settled.
        /// </summary>
        [EnumMember(Value = "SETTLED")]
        Settled,

        /// <summary>
        /// Cancelled.
        /// </summary>
        [EnumMember(Value = "CANCELLED")]
        Cancelled
    }
}