// <copyright file="Status85.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// Status85.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Status85
    {
        /// <summary>
        /// New.
        /// </summary>
        [EnumMember(Value = "NEW")]
        New,

        /// <summary>
        /// Discovery.
        /// </summary>
        [EnumMember(Value = "DISCOVERY")]
        Discovery,

        /// <summary>
        /// DiscoveryConfirmed.
        /// </summary>
        [EnumMember(Value = "DISCOVERY_CONFIRMED")]
        DiscoveryConfirmed,

        /// <summary>
        /// Instructed.
        /// </summary>
        [EnumMember(Value = "INSTRUCTED")]
        Instructed,

        /// <summary>
        /// Processing.
        /// </summary>
        [EnumMember(Value = "PROCESSING")]
        Processing,

        /// <summary>
        /// Settled.
        /// </summary>
        [EnumMember(Value = "SETTLED")]
        Settled
    }
}