// <copyright file="Status109.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// Status109.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Status109
    {
        /// <summary>
        /// InProgress.
        /// </summary>
        [EnumMember(Value = "IN_PROGRESS")]
        InProgress,

        /// <summary>
        /// Passed.
        /// </summary>
        [EnumMember(Value = "PASSED")]
        Passed,

        /// <summary>
        /// Failed.
        /// </summary>
        [EnumMember(Value = "FAILED")]
        Failed
    }
}