// <copyright file="Status56.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// Status56.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Status56
    {
        /// <summary>
        /// New.
        /// </summary>
        [EnumMember(Value = "NEW")]
        New,

        /// <summary>
        /// Active.
        /// </summary>
        [EnumMember(Value = "ACTIVE")]
        Active,

        /// <summary>
        /// Inactive.
        /// </summary>
        [EnumMember(Value = "INACTIVE")]
        Inactive,

        /// <summary>
        /// Closed.
        /// </summary>
        [EnumMember(Value = "CLOSED")]
        Closed
    }
}