// <copyright file="TaxExemptionsUpdateResponse.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// TaxExemptionsUpdateResponse.
    /// </summary>
    public class TaxExemptionsUpdateResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TaxExemptionsUpdateResponse"/> class.
        /// </summary>
        public TaxExemptionsUpdateResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TaxExemptionsUpdateResponse"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        public TaxExemptionsUpdateResponse(
            Guid? id = null)
        {
            this.Id = id;
        }

        /// <summary>
        /// Tax Exemption Unique Identifier
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public Guid? Id { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"TaxExemptionsUpdateResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {(this.Id == null ? "null" : this.Id.ToString())}");
        }
    }
}