// <copyright file="TaxWrappersIsaAllowance.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// TaxWrappersIsaAllowance.
    /// </summary>
    public class TaxWrappersIsaAllowance
    {
        private string taxYear;
        private DateTime? validTo;
        private DateTime? firstSubscriptionAt;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "tax_year", false },
            { "valid_to", false },
            { "first_subscription_at", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="TaxWrappersIsaAllowance"/> class.
        /// </summary>
        public TaxWrappersIsaAllowance()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TaxWrappersIsaAllowance"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="createdAt">created_at.</param>
        /// <param name="updatedAt">updated_at.</param>
        /// <param name="taxWrapperId">tax_wrapper_id.</param>
        /// <param name="type">type.</param>
        /// <param name="status">status.</param>
        /// <param name="currency">currency.</param>
        /// <param name="usedAmount">used_amount.</param>
        /// <param name="remainingAmount">remaining_amount.</param>
        /// <param name="validFrom">valid_from.</param>
        /// <param name="taxYear">tax_year.</param>
        /// <param name="validTo">valid_to.</param>
        /// <param name="firstSubscriptionAt">first_subscription_at.</param>
        public TaxWrappersIsaAllowance(
            Guid id,
            DateTime createdAt,
            DateTime updatedAt,
            Guid taxWrapperId,
            string type,
            Models.Status57 status,
            string currency,
            string usedAmount,
            string remainingAmount,
            DateTime validFrom,
            string taxYear = null,
            DateTime? validTo = null,
            DateTime? firstSubscriptionAt = null)
        {
            this.Id = id;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.TaxWrapperId = taxWrapperId;

            if (taxYear != null)
            {
                this.TaxYear = taxYear;
            }
            this.Type = type;
            this.Status = status;
            this.Currency = currency;
            this.UsedAmount = usedAmount;
            this.RemainingAmount = remainingAmount;
            this.ValidFrom = validFrom;

            if (validTo != null)
            {
                this.ValidTo = validTo;
            }

            if (firstSubscriptionAt != null)
            {
                this.FirstSubscriptionAt = firstSubscriptionAt;
            }
        }

        /// <summary>
        /// Allowance unique identifier.
        /// </summary>
        [JsonProperty("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// The date and time the tax wrapper was created.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// The date and time the tax wrapper was last updated.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("updated_at")]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Tax wrapper unique identifier.
        /// </summary>
        [JsonProperty("tax_wrapper_id")]
        public Guid TaxWrapperId { get; set; }

        /// <summary>
        /// Gets or sets TaxYear.
        /// </summary>
        [JsonProperty("tax_year")]
        public string TaxYear
        {
            get
            {
                return this.taxYear;
            }

            set
            {
                this.shouldSerialize["tax_year"] = true;
                this.taxYear = value;
            }
        }

        /// <summary>
        /// Type of the allowance:
        /// * ANNUAL - Allowance valid for a tax year.
        /// </summary>
        [JsonProperty("type")]
        public string Type { get; set; }

        /// <summary>
        /// Status of the allowance:
        /// * ACTIVE - Current allowance.
        /// * EXPIRED - Allowance from previous years.
        /// </summary>
        [JsonProperty("status")]
        public Models.Status57 Status { get; set; }

        /// <summary>
        /// Alphabetic three-letter [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) currency code.
        /// * GBP - British Pound Sterling
        /// </summary>
        [JsonProperty("currency")]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or sets UsedAmount.
        /// </summary>
        [JsonProperty("used_amount")]
        public string UsedAmount { get; set; }

        /// <summary>
        /// Gets or sets RemainingAmount.
        /// </summary>
        [JsonProperty("remaining_amount")]
        public string RemainingAmount { get; set; }

        /// <summary>
        /// The date from which the allowance is valid.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("valid_from")]
        public DateTime ValidFrom { get; set; }

        /// <summary>
        /// Gets or sets ValidTo.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("valid_to")]
        public DateTime? ValidTo
        {
            get
            {
                return this.validTo;
            }

            set
            {
                this.shouldSerialize["valid_to"] = true;
                this.validTo = value;
            }
        }

        /// <summary>
        /// Gets or sets FirstSubscriptionAt.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("first_subscription_at")]
        public DateTime? FirstSubscriptionAt
        {
            get
            {
                return this.firstSubscriptionAt;
            }

            set
            {
                this.shouldSerialize["first_subscription_at"] = true;
                this.firstSubscriptionAt = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"TaxWrappersIsaAllowance : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetTaxYear()
        {
            this.shouldSerialize["tax_year"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetValidTo()
        {
            this.shouldSerialize["valid_to"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetFirstSubscriptionAt()
        {
            this.shouldSerialize["first_subscription_at"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeTaxYear()
        {
            return this.shouldSerialize["tax_year"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeValidTo()
        {
            return this.shouldSerialize["valid_to"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeFirstSubscriptionAt()
        {
            return this.shouldSerialize["first_subscription_at"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {this.Id}");
            toStringOutput.Add($"CreatedAt = {this.CreatedAt}");
            toStringOutput.Add($"UpdatedAt = {this.UpdatedAt}");
            toStringOutput.Add($"TaxWrapperId = {this.TaxWrapperId}");
            toStringOutput.Add($"TaxYear = {this.TaxYear ?? "null"}");
            toStringOutput.Add($"Type = {this.Type ?? "null"}");
            toStringOutput.Add($"Status = {this.Status}");
            toStringOutput.Add($"Currency = {this.Currency ?? "null"}");
            toStringOutput.Add($"UsedAmount = {this.UsedAmount ?? "null"}");
            toStringOutput.Add($"RemainingAmount = {this.RemainingAmount ?? "null"}");
            toStringOutput.Add($"ValidFrom = {this.ValidFrom}");
            toStringOutput.Add($"ValidTo = {(this.ValidTo == null ? "null" : this.ValidTo.ToString())}");
            toStringOutput.Add($"FirstSubscriptionAt = {(this.FirstSubscriptionAt == null ? "null" : this.FirstSubscriptionAt.ToString())}");
        }
    }
}