// <copyright file="TotalSecurityValue.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// TotalSecurityValue.
    /// </summary>
    public class TotalSecurityValue
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TotalSecurityValue"/> class.
        /// </summary>
        public TotalSecurityValue()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TotalSecurityValue"/> class.
        /// </summary>
        /// <param name="amount">amount.</param>
        /// <param name="currency">currency.</param>
        public TotalSecurityValue(
            string amount,
            Models.Currency currency)
        {
            this.Amount = amount;
            this.Currency = currency;
        }

        /// <summary>
        /// A decimal-string monetary amount used in account valuation calculations.
        /// </summary>
        [JsonProperty("amount")]
        public string Amount { get; set; }

        /// <summary>
        /// Alphabetic three-letter [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) currency code.
        /// * EUR — Euro.
        /// * GBP — Pound Sterling.
        /// </summary>
        [JsonProperty("currency")]
        public Models.Currency Currency { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"TotalSecurityValue : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Amount = {this.Amount ?? "null"}");
            toStringOutput.Add($"Currency = {this.Currency}");
        }
    }
}