// <copyright file="TransactionCategory.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// TransactionCategory.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum TransactionCategory
    {
        /// <summary>
        /// PensionDeContribution.
        /// </summary>
        [EnumMember(Value = "PENSION_DE_CONTRIBUTION")]
        PensionDeContribution,

        /// <summary>
        /// PensionDeContributionGovernmentBonus.
        /// </summary>
        [EnumMember(Value = "PENSION_DE_CONTRIBUTION_GOVERNMENT_BONUS")]
        PensionDeContributionGovernmentBonus,

        /// <summary>
        /// PensionDeIncomingTransfer.
        /// </summary>
        [EnumMember(Value = "PENSION_DE_INCOMING_TRANSFER")]
        PensionDeIncomingTransfer,

        /// <summary>
        /// PensionDeOutgoingTransfer.
        /// </summary>
        [EnumMember(Value = "PENSION_DE_OUTGOING_TRANSFER")]
        PensionDeOutgoingTransfer
    }
}