// <copyright file="TransfersSecuritiesTransferCreateRequest.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using UpvestInvestmentApi.Standard.Utilities;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// TransfersSecuritiesTransferCreateRequest.
    /// </summary>
    public class TransfersSecuritiesTransferCreateRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransfersSecuritiesTransferCreateRequest"/> class.
        /// </summary>
        public TransfersSecuritiesTransferCreateRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransfersSecuritiesTransferCreateRequest"/> class.
        /// </summary>
        /// <param name="direction">direction.</param>
        /// <param name="instrumentId">instrument_id.</param>
        /// <param name="instrumentIdType">instrument_id_type.</param>
        /// <param name="quantity">quantity.</param>
        /// <param name="transferType">transfer_type.</param>
        /// <param name="userId">user_id.</param>
        /// <param name="accountId">account_id.</param>
        /// <param name="settlementReference">settlement_reference.</param>
        /// <param name="counterparty">counterparty.</param>
        /// <param name="placeOfSettlement">place_of_settlement.</param>
        /// <param name="settlementCounterparties">settlement_counterparties.</param>
        /// <param name="tradeDate">trade_date.</param>
        /// <param name="settlementDate">settlement_date.</param>
        /// <param name="orderDate">order_date.</param>
        public TransfersSecuritiesTransferCreateRequest(
            Models.Direction1 direction,
            string instrumentId,
            string instrumentIdType,
            string quantity,
            string transferType,
            Guid userId,
            Guid accountId,
            string settlementReference,
            Models.SecuritiesTransferCounterpartyBic counterparty,
            string placeOfSettlement = null,
            Models.SettlementCounterparties settlementCounterparties = null,
            DateTime? tradeDate = null,
            DateTime? settlementDate = null,
            DateTime? orderDate = null)
        {
            this.Direction = direction;
            this.InstrumentId = instrumentId;
            this.InstrumentIdType = instrumentIdType;
            this.Quantity = quantity;
            this.TransferType = transferType;
            this.UserId = userId;
            this.AccountId = accountId;
            this.PlaceOfSettlement = placeOfSettlement;
            this.SettlementReference = settlementReference;
            this.Counterparty = counterparty;
            this.SettlementCounterparties = settlementCounterparties;
            this.TradeDate = tradeDate;
            this.SettlementDate = settlementDate;
            this.OrderDate = orderDate;
        }

        /// <summary>
        /// Direction of the securities transfer
        /// * `INCOMING` - Securities transfer is incoming to the user.
        /// * `OUTGOING` - Securities transfer is outgoing from the user.
        /// </summary>
        [JsonProperty("direction")]
        public Models.Direction1 Direction { get; set; }

        /// <summary>
        /// `ISIN` or other identity (depends on instrument_id_type) of the security to be transferred.
        /// </summary>
        [JsonProperty("instrument_id")]
        public string InstrumentId { get; set; }

        /// <summary>
        /// The kind of identifier given in `instrument_id`.
        /// * ISIN — International Securities Identification Number.
        /// </summary>
        [JsonProperty("instrument_id_type")]
        public string InstrumentIdType { get; set; }

        /// <summary>
        /// The quantity of the instrument to move in or out, as a decimal string of at most 15 digits including the decimal place. Only full units settle; fractional quantities are not supported by the SWIFT messaging used for settlement.
        /// </summary>
        [JsonProperty("quantity")]
        public string Quantity { get; set; }

        /// <summary>
        /// Type of the securities transfer
        /// * NO_OWNER_CHANGE - No change of ownership.
        /// </summary>
        [JsonProperty("transfer_type")]
        public string TransferType { get; set; }

        /// <summary>
        /// Unique identifier of the user, as a UUID.
        /// </summary>
        [JsonProperty("user_id")]
        public Guid UserId { get; set; }

        /// <summary>
        /// Universally Unique Identifier (UUID) of the account.
        /// </summary>
        [JsonProperty("account_id")]
        public Guid AccountId { get; set; }

        /// <summary>
        /// Business Identifier Code (also known as SWIFT-BIC, BIC, SWIFT ID or SWIFT code) [ISO 9362](https://en.wikipedia.org/wiki/ISO_9362).
        /// </summary>
        [JsonProperty("place_of_settlement", NullValueHandling = NullValueHandling.Ignore)]
        public string PlaceOfSettlement { get; set; }

        /// <summary>
        /// A reference for the securities transfer, set by the client and useful for correlating the transfer with client-side records. For automatic incoming transfers, where the client subscribes to the corresponding webhook, Upvest sets this value.
        /// </summary>
        [JsonProperty("settlement_reference")]
        public string SettlementReference { get; set; }

        /// <summary>
        /// Counterparty for securities transfer. The `type` field determines which counterparty variant is present in the payload.
        /// </summary>
        [JsonProperty("counterparty")]
        public Models.SecuritiesTransferCounterpartyBic Counterparty { get; set; }

        /// <summary>
        /// Settlement counterparties for the securities transfer.
        /// When `settlement_counterparties` is provided, `settlement_agent` is required. Other participants are optional but must respect the following dependency rules:
        /// * `settlement_custodian` presence requires `settlement_party` to be present.
        /// * `settlement_intermediary_1` presence requires `settlement_custodian` to be present.
        /// * `settlement_intermediary_2` presence requires `settlement_intermediary_1` to be present.
        ///  Note: `settlement_custodian` can be provided without an explicit `settlement_party` since the default `counterparty` field at transfer level serves as the settlement party.
        /// </summary>
        [JsonProperty("settlement_counterparties", NullValueHandling = NullValueHandling.Ignore)]
        public Models.SettlementCounterparties SettlementCounterparties { get; set; }

        /// <summary>
        /// Optional forecast date when the trade takes place. If provided, usually T+1 is sufficient. Depending on the market this means valid working days. Date in YYYY-MM-DD format.
        /// </summary>
        [JsonConverter(typeof(CustomDateTimeConverter), "yyyy'-'MM'-'dd")]
        [JsonProperty("trade_date", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? TradeDate { get; set; }

        /// <summary>
        /// Optional forecast date when the settlement takes place. If provided, usually T+2 is sufficient or trade_date + 1. Depending on the market this means valid working days. Date in YYYY-MM-DD format.
        /// </summary>
        [JsonConverter(typeof(CustomDateTimeConverter), "yyyy'-'MM'-'dd")]
        [JsonProperty("settlement_date", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? SettlementDate { get; set; }

        /// <summary>
        /// Optional date when the transfer request was received from the end user. If omitted, Upvest defaults `order_date` to the transfer's `created_at` timestamp. The regulatory deadline runs from this date. Date in YYYY-MM-DD format.
        /// </summary>
        [JsonConverter(typeof(CustomDateTimeConverter), "yyyy'-'MM'-'dd")]
        [JsonProperty("order_date", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? OrderDate { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"TransfersSecuritiesTransferCreateRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Direction = {this.Direction}");
            toStringOutput.Add($"InstrumentId = {this.InstrumentId ?? "null"}");
            toStringOutput.Add($"InstrumentIdType = {this.InstrumentIdType ?? "null"}");
            toStringOutput.Add($"Quantity = {this.Quantity ?? "null"}");
            toStringOutput.Add($"TransferType = {this.TransferType ?? "null"}");
            toStringOutput.Add($"UserId = {this.UserId}");
            toStringOutput.Add($"AccountId = {this.AccountId}");
            toStringOutput.Add($"PlaceOfSettlement = {this.PlaceOfSettlement ?? "null"}");
            toStringOutput.Add($"SettlementReference = {this.SettlementReference ?? "null"}");
            toStringOutput.Add($"Counterparty = {(this.Counterparty == null ? "null" : this.Counterparty.ToString())}");
            toStringOutput.Add($"SettlementCounterparties = {(this.SettlementCounterparties == null ? "null" : this.SettlementCounterparties.ToString())}");
            toStringOutput.Add($"TradeDate = {(this.TradeDate == null ? "null" : this.TradeDate.ToString())}");
            toStringOutput.Add($"SettlementDate = {(this.SettlementDate == null ? "null" : this.SettlementDate.ToString())}");
            toStringOutput.Add($"OrderDate = {(this.OrderDate == null ? "null" : this.OrderDate.ToString())}");
        }
    }
}