// <copyright file="TransactionFeeAccountGroupConfiguration.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// TransactionFeeAccountGroupConfiguration.
    /// </summary>
    public class TransactionFeeAccountGroupConfiguration
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionFeeAccountGroupConfiguration"/> class.
        /// </summary>
        public TransactionFeeAccountGroupConfiguration()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionFeeAccountGroupConfiguration"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="createdAt">created_at.</param>
        /// <param name="updatedAt">updated_at.</param>
        /// <param name="feeModelId">fee_model_id.</param>
        /// <param name="accountGroupId">account_group_id.</param>
        /// <param name="transactionCategory">transaction_category.</param>
        public TransactionFeeAccountGroupConfiguration(
            Guid id,
            DateTime createdAt,
            DateTime updatedAt,
            Guid feeModelId,
            Guid accountGroupId,
            Models.TransactionCategory transactionCategory)
        {
            this.Id = id;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.FeeModelId = feeModelId;
            this.AccountGroupId = accountGroupId;
            this.TransactionCategory = transactionCategory;
        }

        /// <summary>
        /// Transaction fee account group configuration unique identifier.
        /// </summary>
        [JsonProperty("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Date and time when the resource was created. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Date and time when the resource was last updated. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("updated_at")]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Universally Unique Identifier (UUID) of the transaction fee model.
        /// </summary>
        [JsonProperty("fee_model_id")]
        public Guid FeeModelId { get; set; }

        /// <summary>
        /// Universally Unique Identifier (UUID) of the account group.
        /// </summary>
        [JsonProperty("account_group_id")]
        public Guid AccountGroupId { get; set; }

        /// <summary>
        /// The operation type a transaction fee model is assigned to.
        /// * PENSION_DE_CONTRIBUTION -
        /// * PENSION_DE_CONTRIBUTION_GOVERNMENT_BONUS -
        /// * PENSION_DE_INCOMING_TRANSFER -
        /// * PENSION_DE_OUTGOING_TRANSFER -
        /// </summary>
        [JsonProperty("transaction_category")]
        public Models.TransactionCategory TransactionCategory { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"TransactionFeeAccountGroupConfiguration : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {this.Id}");
            toStringOutput.Add($"CreatedAt = {this.CreatedAt}");
            toStringOutput.Add($"UpdatedAt = {this.UpdatedAt}");
            toStringOutput.Add($"FeeModelId = {this.FeeModelId}");
            toStringOutput.Add($"AccountGroupId = {this.AccountGroupId}");
            toStringOutput.Add($"TransactionCategory = {this.TransactionCategory}");
        }
    }
}