// <copyright file="Type51.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// Type51.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Type51
    {
        /// <summary>
        /// Order.
        /// </summary>
        [EnumMember(Value = "ORDER")]
        Order,

        /// <summary>
        /// OrderExecution.
        /// </summary>
        [EnumMember(Value = "ORDER_EXECUTION")]
        OrderExecution,

        /// <summary>
        /// CorporateAction.
        /// </summary>
        [EnumMember(Value = "CORPORATE_ACTION")]
        CorporateAction,

        /// <summary>
        /// CorporateActionTransactionId.
        /// </summary>
        [EnumMember(Value = "CORPORATE_ACTION_TRANSACTION_ID")]
        CorporateActionTransactionId
    }
}