// <copyright file="Type7.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// Type7.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Type7
    {
        /// <summary>
        /// NationalId.
        /// </summary>
        [EnumMember(Value = "NATIONAL_ID")]
        NationalId,

        /// <summary>
        /// Passport.
        /// </summary>
        [EnumMember(Value = "PASSPORT")]
        Passport
    }
}