// <copyright file="Type52.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// Type52.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Type52
    {
        /// <summary>
        /// Bic.
        /// </summary>
        [EnumMember(Value = "BIC")]
        Bic,

        /// <summary>
        /// Proprietary.
        /// </summary>
        [EnumMember(Value = "PROPRIETARY")]
        Proprietary,

        /// <summary>
        /// NameAndAddress.
        /// </summary>
        [EnumMember(Value = "NAME_AND_ADDRESS")]
        NameAndAddress
    }
}