// <copyright file="Type50.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// Type50.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Type50
    {
        /// <summary>
        /// AccountGroup.
        /// </summary>
        [EnumMember(Value = "ACCOUNT_GROUP")]
        AccountGroup,

        /// <summary>
        /// CashBalanceTransfer.
        /// </summary>
        [EnumMember(Value = "CASH_BALANCE_TRANSFER")]
        CashBalanceTransfer,

        /// <summary>
        /// CorporateAction.
        /// </summary>
        [EnumMember(Value = "CORPORATE_ACTION")]
        CorporateAction,

        /// <summary>
        /// CorporateActionTransactionId.
        /// </summary>
        [EnumMember(Value = "CORPORATE_ACTION_TRANSACTION_ID")]
        CorporateActionTransactionId,

        /// <summary>
        /// CreditFunding.
        /// </summary>
        [EnumMember(Value = "CREDIT_FUNDING")]
        CreditFunding,

        /// <summary>
        /// DirectDebit.
        /// </summary>
        [EnumMember(Value = "DIRECT_DEBIT")]
        DirectDebit,

        /// <summary>
        /// ExternalDirectDebit.
        /// </summary>
        [EnumMember(Value = "EXTERNAL_DIRECT_DEBIT")]
        ExternalDirectDebit,

        /// <summary>
        /// FeeCollection.
        /// </summary>
        [EnumMember(Value = "FEE_COLLECTION")]
        FeeCollection,

        /// <summary>
        /// IsaTransfer.
        /// </summary>
        [EnumMember(Value = "ISA_TRANSFER")]
        IsaTransfer,

        /// <summary>
        /// Order.
        /// </summary>
        [EnumMember(Value = "ORDER")]
        Order,

        /// <summary>
        /// OrderExecution.
        /// </summary>
        [EnumMember(Value = "ORDER_EXECUTION")]
        OrderExecution,

        /// <summary>
        /// TaxTransaction.
        /// </summary>
        [EnumMember(Value = "TAX_TRANSACTION")]
        TaxTransaction,

        /// <summary>
        /// Topup.
        /// </summary>
        [EnumMember(Value = "TOPUP")]
        Topup,

        /// <summary>
        /// TransactionFeeExecution.
        /// </summary>
        [EnumMember(Value = "TRANSACTION_FEE_EXECUTION")]
        TransactionFeeExecution,

        /// <summary>
        /// VirtualCashDecrease.
        /// </summary>
        [EnumMember(Value = "VIRTUAL_CASH_DECREASE")]
        VirtualCashDecrease,

        /// <summary>
        /// VirtualCashIncrease.
        /// </summary>
        [EnumMember(Value = "VIRTUAL_CASH_INCREASE")]
        VirtualCashIncrease,

        /// <summary>
        /// Withdrawal.
        /// </summary>
        [EnumMember(Value = "WITHDRAWAL")]
        Withdrawal
    }
}