// <copyright file="Unit.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// Unit.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Unit
    {
        /// <summary>
        /// Year.
        /// </summary>
        [EnumMember(Value = "YEAR")]
        Year
    }
}