// <copyright file="UserTolDataChangeRequestNationality.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using UpvestInvestmentApi.Standard.Utilities;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// UserTolDataChangeRequestNationality.
    /// </summary>
    public class UserTolDataChangeRequestNationality
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserTolDataChangeRequestNationality"/> class.
        /// </summary>
        public UserTolDataChangeRequestNationality()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserTolDataChangeRequestNationality"/> class.
        /// </summary>
        /// <param name="nationalities">nationalities.</param>
        /// <param name="issuanceDate">issuance_date.</param>
        /// <param name="dataDownloadLink">data_download_link.</param>
        /// <param name="documentType">document_type.</param>
        public UserTolDataChangeRequestNationality(
            List<Models.Nationality> nationalities,
            DateTime issuanceDate,
            string dataDownloadLink,
            Models.DocumentType documentType)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Nationalities = nationalities;
            this.IssuanceDate = issuanceDate;
            this.DataDownloadLink = dataDownloadLink;
            this.DocumentType = documentType;
        }

        /// <summary>
        /// Nationalities of the user. [ISO 3166 alpha-2 Codes](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
        /// </summary>
        [JsonProperty("nationalities")]
        [JsonRequired]
        public List<Models.Nationality> Nationalities { get; set; }

        /// <summary>
        /// Issuance date in YYYY-MM-DD format. [RFC 3339, section 5.6](https://json-schema.org/draft/2020-12/json-schema-validation.html#RFC3339)
        /// </summary>
        [JsonConverter(typeof(CustomDateTimeConverter), "yyyy'-'MM'-'dd")]
        [JsonProperty("issuance_date")]
        [JsonRequired]
        public DateTime IssuanceDate { get; set; }

        /// <summary>
        /// Download URL for the document proving the data change. The file size must not exceed 250 MB.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("data_download_link")]
        [JsonRequired]
        public string DataDownloadLink { get; set; }

        /// <summary>
        /// The type of document used to prove the data change
        /// * PASSPORT - Passport
        /// * ID_CARD - National Identification document
        /// </summary>
        [JsonProperty("document_type")]
        [JsonRequired]
        public Models.DocumentType DocumentType { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"UserTolDataChangeRequestNationality : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Nationalities = {(this.Nationalities == null ? "null" : $"[{string.Join(", ", this.Nationalities)} ]")}");
            toStringOutput.Add($"IssuanceDate = {this.IssuanceDate}");
            toStringOutput.Add($"DataDownloadLink = {this.DataDownloadLink ?? "null"}");
            toStringOutput.Add($"DocumentType = {this.DocumentType}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}