// <copyright file="UserCheckUsWithholdingTaxStatus.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using UpvestInvestmentApi.Standard.Utilities;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// UserCheckUsWithholdingTaxStatus.
    /// </summary>
    public class UserCheckUsWithholdingTaxStatus
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private DateTime? validTo;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "valid_to", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="UserCheckUsWithholdingTaxStatus"/> class.
        /// </summary>
        public UserCheckUsWithholdingTaxStatus()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserCheckUsWithholdingTaxStatus"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="userId">user_id.</param>
        /// <param name="type">type.</param>
        /// <param name="checkConfirmedAt">check_confirmed_at.</param>
        /// <param name="personType">person_type.</param>
        /// <param name="documentationType">documentation_type.</param>
        /// <param name="validFrom">valid_from.</param>
        /// <param name="status">status.</param>
        /// <param name="dataDownloadLink">data_download_link.</param>
        /// <param name="validTo">valid_to.</param>
        public UserCheckUsWithholdingTaxStatus(
            Guid id,
            Guid userId,
            string type,
            DateTime checkConfirmedAt,
            Models.UserPersonType personType,
            Models.UserDocumentationType documentationType,
            DateTime validFrom,
            Models.Status11 status,
            string dataDownloadLink = null,
            DateTime? validTo = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Id = id;
            this.UserId = userId;
            this.Type = type;
            this.CheckConfirmedAt = checkConfirmedAt;
            this.DataDownloadLink = dataDownloadLink;
            this.PersonType = personType;
            this.DocumentationType = documentationType;
            this.ValidFrom = validFrom;

            if (validTo != null)
            {
                this.ValidTo = validTo;
            }
            this.Status = status;
        }

        /// <summary>
        /// User Check unique identifier.
        /// </summary>
        [JsonProperty("id")]
        [JsonRequired]
        public Guid Id { get; set; }

        /// <summary>
        /// Unique identifier of the user, as a UUID.
        /// </summary>
        [JsonProperty("user_id")]
        [JsonRequired]
        public Guid UserId { get; set; }

        /// <summary>
        /// The type of check must be "US_WITHHOLDING_TAX_STATUS".
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("type")]
        [JsonRequired]
        public string Type { get; set; }

        /// <summary>
        /// The date and time when the US withholding tax status was confirmed.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("check_confirmed_at")]
        [JsonRequired]
        public DateTime CheckConfirmedAt { get; set; }

        /// <summary>
        /// Download URL for the withholding status evidence file. Only required when `documentation_type` is "W8-BEN" or "W9", and only when your operating model requires supporting documents to be supplied to Upvest. The file size must not exceed 250 MB.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("data_download_link", NullValueHandling = NullValueHandling.Ignore)]
        public string DataDownloadLink { get; set; }

        /// <summary>
        /// US tax person classification of the user.
        /// * US_PERSON - The user is a US person for tax purposes.
        /// * NON_RESIDENT_ALIEN - The user is a non-resident alien for US tax purposes.
        /// </summary>
        [JsonProperty("person_type")]
        [JsonRequired]
        public Models.UserPersonType PersonType { get; set; }

        /// <summary>
        /// Type of documentation supporting the US withholding tax status.
        /// * KYC - Withholding status derived from the existing KYC data (non-resident aliens only).
        /// * W8-BEN - IRS Form W-8BEN provided by the user (non-resident aliens only).
        /// * W9 - IRS Form W-9 provided by the user (US persons only).
        /// * UNDOCUMENTED - No documentation is available for the user.
        /// For a non-resident alien, "KYC" is accepted for every operating model; whether "W8-BEN" and "UNDOCUMENTED" are also accepted depends on your operating model.
        /// </summary>
        [JsonProperty("documentation_type")]
        [JsonRequired]
        public Models.UserDocumentationType DocumentationType { get; set; }

        /// <summary>
        /// The date from which the US withholding tax status is valid, in YYYY-MM-DD format.
        /// </summary>
        [JsonConverter(typeof(CustomDateTimeConverter), "yyyy'-'MM'-'dd")]
        [JsonProperty("valid_from")]
        [JsonRequired]
        public DateTime ValidFrom { get; set; }

        /// <summary>
        /// The date until which the US withholding tax status is valid, in YYYY-MM-DD format. Null if the status has no defined end date.
        /// </summary>
        [JsonConverter(typeof(CustomDateTimeConverter), "yyyy'-'MM'-'dd")]
        [JsonProperty("valid_to")]
        public DateTime? ValidTo
        {
            get
            {
                return this.validTo;
            }

            set
            {
                this.shouldSerialize["valid_to"] = true;
                this.validTo = value;
            }
        }

        /// <summary>
        /// Final status of the US Withholding Tax Status check.
        /// * IN_PROGRESS - US Withholding Tax Status check is in progress
        /// * PASSED - US Withholding Tax Status check passed
        /// * FAILED - US Withholding Tax Status check failed
        /// A documented status ("KYC", "W8-BEN" or "W9") is corroborated against the user's tax residency: it fails when the declared `person_type` contradicts the tax residency Upvest holds for the user, or when the user has no active tax residency on record. An "UNDOCUMENTED" status is recorded as declared and is not corroborated against tax residency.
        /// </summary>
        [JsonProperty("status")]
        [JsonRequired]
        public Models.Status11 Status { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"UserCheckUsWithholdingTaxStatus : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetValidTo()
        {
            this.shouldSerialize["valid_to"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeValidTo()
        {
            return this.shouldSerialize["valid_to"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {this.Id}");
            toStringOutput.Add($"UserId = {this.UserId}");
            toStringOutput.Add($"Type = {this.Type ?? "null"}");
            toStringOutput.Add($"CheckConfirmedAt = {this.CheckConfirmedAt}");
            toStringOutput.Add($"DataDownloadLink = {this.DataDownloadLink ?? "null"}");
            toStringOutput.Add($"PersonType = {this.PersonType}");
            toStringOutput.Add($"DocumentationType = {this.DocumentationType}");
            toStringOutput.Add($"ValidFrom = {this.ValidFrom}");
            toStringOutput.Add($"ValidTo = {(this.ValidTo == null ? "null" : this.ValidTo.ToString())}");
            toStringOutput.Add($"Status = {this.Status}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}