// <copyright file="VirtualCashBalanceVirtualCashDecreaseCreateRequest.cs" company="APIMatic">
// UpvestInvestmentApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace UpvestInvestmentApi.Standard.Models
{
    /// <summary>
    /// VirtualCashBalanceVirtualCashDecreaseCreateRequest.
    /// </summary>
    public class VirtualCashBalanceVirtualCashDecreaseCreateRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VirtualCashBalanceVirtualCashDecreaseCreateRequest"/> class.
        /// </summary>
        public VirtualCashBalanceVirtualCashDecreaseCreateRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="VirtualCashBalanceVirtualCashDecreaseCreateRequest"/> class.
        /// </summary>
        /// <param name="accountGroupId">account_group_id.</param>
        /// <param name="amount">amount.</param>
        /// <param name="currency">currency.</param>
        public VirtualCashBalanceVirtualCashDecreaseCreateRequest(
            Guid accountGroupId,
            string amount,
            Models.Currency1 currency)
        {
            this.AccountGroupId = accountGroupId;
            this.Amount = amount;
            this.Currency = currency;
        }

        /// <summary>
        /// Universally Unique Identifier (UUID) of the account group.
        /// </summary>
        [JsonProperty("account_group_id")]
        public Guid AccountGroupId { get; set; }

        /// <summary>
        /// A positive cash amount, as a decimal string with up to two decimal places.
        /// </summary>
        [JsonProperty("amount")]
        public string Amount { get; set; }

        /// <summary>
        /// Alphabetic three-letter [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) currency code.
        /// * EUR — Euro.
        /// * GBP — Pound Sterling.
        /// * USD — The United States dollar.
        /// </summary>
        [JsonProperty("currency")]
        public Models.Currency1 Currency { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"VirtualCashBalanceVirtualCashDecreaseCreateRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AccountGroupId = {this.AccountGroupId}");
            toStringOutput.Add($"Amount = {this.Amount ?? "null"}");
            toStringOutput.Add($"Currency = {this.Currency}");
        }
    }
}